"use strict";

const testExports = require("../testExports");

test("exports", () => {
  expect(testExports("yup")).toMatchInlineSnapshot(`
    [
      [
        "array",
        "create",
        "yup/es/array.js",
      ],
      [
        "ArraySchema",
        "default",
        "yup/es/array.js",
      ],
      [
        "bool",
        "create",
        "yup/es/boolean.js",
      ],
      [
        "boolean",
        "create",
        "yup/es/boolean.js",
      ],
      [
        "BooleanSchema",
        "default",
        "yup/es/boolean.js",
      ],
      [
        "date",
        "create",
        "yup/es/date.js",
      ],
      [
        "DateSchema",
        "default",
        "yup/es/date.js",
      ],
      [
        "addMethod",
        "addMethod",
        "yup/es/index.js",
      ],
      [
        "lazy",
        "create",
        "yup/es/Lazy.js",
      ],
      [
        "mixed",
        "create",
        "yup/es/mixed.js",
      ],
      [
        "MixedSchema",
        "default",
        "yup/es/mixed.js",
      ],
      [
        "number",
        "create",
        "yup/es/number.js",
      ],
      [
        "NumberSchema",
        "default",
        "yup/es/number.js",
      ],
      [
        "object",
        "create",
        "yup/es/object.js",
      ],
      [
        "ObjectSchema",
        "default",
        "yup/es/object.js",
      ],
      [
        "ref",
        "create",
        "yup/es/Reference.js",
      ],
      [
        "BaseSchema",
        "default",
        "yup/es/schema.js",
      ],
      [
        "setLocale",
        "default",
        "yup/es/setLocale.js",
      ],
      [
        "string",
        "create",
        "yup/es/string.js",
      ],
      [
        "StringSchema",
        "default",
        "yup/es/string.js",
      ],
      [
        "isSchema",
        "default",
        "yup/es/util/isSchema.js",
      ],
      [
        "reach",
        "default",
        "yup/es/util/reach.js",
      ],
      [
        "ValidationError",
        "default",
        "yup/es/ValidationError.js",
      ],
    ]
  `);
});
