import { expect, test } from "vitest";
import { testExports } from "../../utils.js";

test("exports", () => {
  expect(testExports("@mui/lab")).toMatchInlineSnapshot(`
    [
      [
        "useAutocomplete",
        "useAutocomplete",
        "@mui/base",
      ],
      [
        "Alert",
        "default",
        "@mui/lab/Alert/Alert.js",
      ],
      [
        "AlertTitle",
        "default",
        "@mui/lab/AlertTitle/AlertTitle.js",
      ],
      [
        "Autocomplete",
        "default",
        "@mui/lab/Autocomplete/Autocomplete.js",
      ],
      [
        "AvatarGroup",
        "default",
        "@mui/lab/AvatarGroup/AvatarGroup.js",
      ],
      [
        "CalendarPicker",
        "default",
        "@mui/lab/CalendarPicker/CalendarPicker.js",
      ],
      [
        "calendarPickerClasses",
        "calendarPickerClasses",
        "@mui/lab/CalendarPicker/CalendarPicker.js",
      ],
      [
        "CalendarPickerSkeleton",
        "default",
        "@mui/lab/CalendarPickerSkeleton/CalendarPickerSkeleton.js",
      ],
      [
        "calendarPickerSkeletonClasses",
        "calendarPickerSkeletonClasses",
        "@mui/lab/CalendarPickerSkeleton/CalendarPickerSkeleton.js",
      ],
      [
        "getCalendarPickerSkeletonUtilityClass",
        "getCalendarPickerSkeletonUtilityClass",
        "@mui/lab/CalendarPickerSkeleton/CalendarPickerSkeleton.js",
      ],
      [
        "ClockPicker",
        "default",
        "@mui/lab/ClockPicker/ClockPicker.js",
      ],
      [
        "clockPickerClasses",
        "clockPickerClasses",
        "@mui/lab/ClockPicker/ClockPicker.js",
      ],
      [
        "DatePicker",
        "default",
        "@mui/lab/DatePicker/DatePicker.js",
      ],
      [
        "DateRangePicker",
        "default",
        "@mui/lab/DateRangePicker/DateRangePicker.js",
      ],
      [
        "DateRangePickerDay",
        "default",
        "@mui/lab/DateRangePickerDay/DateRangePickerDay.js",
      ],
      [
        "getDateRangePickerDayUtilityClass",
        "getDateRangePickerDayUtilityClass",
        "@mui/lab/DateRangePickerDay/DateRangePickerDay.js",
      ],
      [
        "DateTimePicker",
        "default",
        "@mui/lab/DateTimePicker/DateTimePicker.js",
      ],
      [
        "DesktopDatePicker",
        "default",
        "@mui/lab/DesktopDatePicker/DesktopDatePicker.js",
      ],
      [
        "DesktopDateRangePicker",
        "default",
        "@mui/lab/DesktopDateRangePicker/DesktopDateRangePicker.js",
      ],
      [
        "DesktopDateTimePicker",
        "default",
        "@mui/lab/DesktopDateTimePicker/DesktopDateTimePicker.js",
      ],
      [
        "DesktopTimePicker",
        "default",
        "@mui/lab/DesktopTimePicker/DesktopTimePicker.js",
      ],
      [
        "LoadingButton",
        "default",
        "@mui/lab/LoadingButton/LoadingButton.js",
      ],
      [
        "loadingButtonClasses",
        "default",
        "@mui/lab/LoadingButton/loadingButtonClasses.js",
      ],
      [
        "getLoadingButtonUtilityClass",
        "getLoadingButtonUtilityClass",
        "@mui/lab/LoadingButton/loadingButtonClasses.js",
      ],
      [
        "LocalizationProvider",
        "default",
        "@mui/lab/LocalizationProvider/LocalizationProvider.js",
      ],
      [
        "Masonry",
        "default",
        "@mui/lab/Masonry/Masonry.js",
      ],
      [
        "getMasonryUtilityClass",
        "getMasonryUtilityClass",
        "@mui/lab/Masonry/masonryClasses.js",
      ],
      [
        "masonryClasses",
        "default",
        "@mui/lab/Masonry/masonryClasses.js",
      ],
      [
        "MobileDatePicker",
        "default",
        "@mui/lab/MobileDatePicker/MobileDatePicker.js",
      ],
      [
        "MobileDateRangePicker",
        "default",
        "@mui/lab/MobileDateRangePicker/MobileDateRangePicker.js",
      ],
      [
        "MobileDateTimePicker",
        "default",
        "@mui/lab/MobileDateTimePicker/MobileDateTimePicker.js",
      ],
      [
        "MobileTimePicker",
        "default",
        "@mui/lab/MobileTimePicker/MobileTimePicker.js",
      ],
      [
        "MonthPicker",
        "default",
        "@mui/lab/MonthPicker/MonthPicker.js",
      ],
      [
        "monthPickerClasses",
        "monthPickerClasses",
        "@mui/lab/MonthPicker/MonthPicker.js",
      ],
      [
        "getMonthPickerUtilityClass",
        "getMonthPickerUtilityClass",
        "@mui/lab/MonthPicker/MonthPicker.js",
      ],
      [
        "Pagination",
        "default",
        "@mui/lab/Pagination/Pagination.js",
      ],
      [
        "PaginationItem",
        "default",
        "@mui/lab/PaginationItem/PaginationItem.js",
      ],
      [
        "PickersDay",
        "default",
        "@mui/lab/PickersDay/PickersDay.js",
      ],
      [
        "pickersDayClasses",
        "pickersDayClasses",
        "@mui/lab/PickersDay/PickersDay.js",
      ],
      [
        "getPickersDayUtilityClass",
        "getPickersDayUtilityClass",
        "@mui/lab/PickersDay/PickersDay.js",
      ],
      [
        "Rating",
        "default",
        "@mui/lab/Rating/Rating.js",
      ],
      [
        "Skeleton",
        "default",
        "@mui/lab/Skeleton/Skeleton.js",
      ],
      [
        "SpeedDial",
        "default",
        "@mui/lab/SpeedDial/SpeedDial.js",
      ],
      [
        "SpeedDialAction",
        "default",
        "@mui/lab/SpeedDialAction/SpeedDialAction.js",
      ],
      [
        "SpeedDialIcon",
        "default",
        "@mui/lab/SpeedDialIcon/SpeedDialIcon.js",
      ],
      [
        "StaticDatePicker",
        "default",
        "@mui/lab/StaticDatePicker/StaticDatePicker.js",
      ],
      [
        "StaticDateRangePicker",
        "default",
        "@mui/lab/StaticDateRangePicker/StaticDateRangePicker.js",
      ],
      [
        "StaticDateTimePicker",
        "default",
        "@mui/lab/StaticDateTimePicker/StaticDateTimePicker.js",
      ],
      [
        "StaticTimePicker",
        "default",
        "@mui/lab/StaticTimePicker/StaticTimePicker.js",
      ],
      [
        "TabContext",
        "default",
        "@mui/lab/TabContext/TabContext.js",
      ],
      [
        "useTabContext",
        "useTabContext",
        "@mui/lab/TabContext/TabContext.js",
      ],
      [
        "getPanelId",
        "getPanelId",
        "@mui/lab/TabContext/TabContext.js",
      ],
      [
        "getTabId",
        "getTabId",
        "@mui/lab/TabContext/TabContext.js",
      ],
      [
        "TabList",
        "default",
        "@mui/lab/TabList/TabList.js",
      ],
      [
        "TabPanel",
        "default",
        "@mui/lab/TabPanel/TabPanel.js",
      ],
      [
        "tabPanelClasses",
        "default",
        "@mui/lab/TabPanel/tabPanelClasses.js",
      ],
      [
        "getTabPanelUtilityClass",
        "getTabPanelUtilityClass",
        "@mui/lab/TabPanel/tabPanelClasses.js",
      ],
      [
        "Timeline",
        "default",
        "@mui/lab/Timeline/Timeline.js",
      ],
      [
        "timelineClasses",
        "default",
        "@mui/lab/Timeline/timelineClasses.js",
      ],
      [
        "getTimelineUtilityClass",
        "getTimelineUtilityClass",
        "@mui/lab/Timeline/timelineClasses.js",
      ],
      [
        "TimelineConnector",
        "default",
        "@mui/lab/TimelineConnector/TimelineConnector.js",
      ],
      [
        "timelineConnectorClasses",
        "default",
        "@mui/lab/TimelineConnector/timelineConnectorClasses.js",
      ],
      [
        "getTimelineConnectorUtilityClass",
        "getTimelineConnectorUtilityClass",
        "@mui/lab/TimelineConnector/timelineConnectorClasses.js",
      ],
      [
        "TimelineContent",
        "default",
        "@mui/lab/TimelineContent/TimelineContent.js",
      ],
      [
        "timelineContentClasses",
        "default",
        "@mui/lab/TimelineContent/timelineContentClasses.js",
      ],
      [
        "getTimelineContentUtilityClass",
        "getTimelineContentUtilityClass",
        "@mui/lab/TimelineContent/timelineContentClasses.js",
      ],
      [
        "TimelineDot",
        "default",
        "@mui/lab/TimelineDot/TimelineDot.js",
      ],
      [
        "timelineDotClasses",
        "default",
        "@mui/lab/TimelineDot/timelineDotClasses.js",
      ],
      [
        "getTimelineDotUtilityClass",
        "getTimelineDotUtilityClass",
        "@mui/lab/TimelineDot/timelineDotClasses.js",
      ],
      [
        "TimelineItem",
        "default",
        "@mui/lab/TimelineItem/TimelineItem.js",
      ],
      [
        "timelineItemClasses",
        "default",
        "@mui/lab/TimelineItem/timelineItemClasses.js",
      ],
      [
        "getTimelineItemUtilityClass",
        "getTimelineItemUtilityClass",
        "@mui/lab/TimelineItem/timelineItemClasses.js",
      ],
      [
        "TimelineOppositeContent",
        "default",
        "@mui/lab/TimelineOppositeContent/TimelineOppositeContent.js",
      ],
      [
        "timelineOppositeContentClasses",
        "default",
        "@mui/lab/TimelineOppositeContent/timelineOppositeContentClasses.js",
      ],
      [
        "getTimelineOppositeContentUtilityClass",
        "getTimelineOppositeContentUtilityClass",
        "@mui/lab/TimelineOppositeContent/timelineOppositeContentClasses.js",
      ],
      [
        "TimelineSeparator",
        "default",
        "@mui/lab/TimelineSeparator/TimelineSeparator.js",
      ],
      [
        "timelineSeparatorClasses",
        "default",
        "@mui/lab/TimelineSeparator/timelineSeparatorClasses.js",
      ],
      [
        "getTimelineSeparatorUtilityClass",
        "getTimelineSeparatorUtilityClass",
        "@mui/lab/TimelineSeparator/timelineSeparatorClasses.js",
      ],
      [
        "TimePicker",
        "default",
        "@mui/lab/TimePicker/TimePicker.js",
      ],
      [
        "ToggleButton",
        "default",
        "@mui/lab/ToggleButton/ToggleButton.js",
      ],
      [
        "ToggleButtonGroup",
        "default",
        "@mui/lab/ToggleButtonGroup/ToggleButtonGroup.js",
      ],
      [
        "TreeItem",
        "default",
        "@mui/lab/TreeItem/TreeItem.js",
      ],
      [
        "treeItemClasses",
        "default",
        "@mui/lab/TreeItem/treeItemClasses.js",
      ],
      [
        "getTreeItemUtilityClass",
        "getTreeItemUtilityClass",
        "@mui/lab/TreeItem/treeItemClasses.js",
      ],
      [
        "useTreeItem",
        "default",
        "@mui/lab/TreeItem/useTreeItem.js",
      ],
      [
        "TreeView",
        "default",
        "@mui/lab/TreeView/TreeView.js",
      ],
      [
        "treeViewClasses",
        "default",
        "@mui/lab/TreeView/treeViewClasses.js",
      ],
      [
        "getTreeViewUtilityClass",
        "getTreeViewUtilityClass",
        "@mui/lab/TreeView/treeViewClasses.js",
      ],
      [
        "YearPicker",
        "default",
        "@mui/lab/YearPicker/YearPicker.js",
      ],
      [
        "yearPickerClasses",
        "yearPickerClasses",
        "@mui/lab/YearPicker/YearPicker.js",
      ],
      [
        "getYearPickerUtilityClass",
        "getYearPickerUtilityClass",
        "@mui/lab/YearPicker/YearPicker.js",
      ],
      [
        "usePagination",
        "default",
        "@mui/material/usePagination",
      ],
    ]
  `);
});
