"use strict";

const testExports = require("../../testExports");

test("exports", () => {
  expect(testExports("@mui/material")).toMatchInlineSnapshot(`
    [
      [
        "ClickAwayListener",
        "default",
        "@mui/base/ClickAwayListener",
      ],
      [
        "unstable_composeClasses",
        "default",
        "@mui/base/composeClasses",
      ],
      [
        "Unstable_TrapFocus",
        "default",
        "@mui/base/FocusTrap",
      ],
      [
        "ModalManager",
        "default",
        "@mui/base/ModalUnstyled/ModalManager.js",
      ],
      [
        "ariaHidden",
        "ariaHidden",
        "@mui/base/ModalUnstyled/ModalManager.js",
      ],
      [
        "modalUnstyledClasses",
        "default",
        "@mui/base/ModalUnstyled/modalUnstyledClasses.js",
      ],
      [
        "getModalUtilityClass",
        "getModalUtilityClass",
        "@mui/base/ModalUnstyled/modalUnstyledClasses.js",
      ],
      [
        "NoSsr",
        "default",
        "@mui/base/NoSsr",
      ],
      [
        "Portal",
        "default",
        "@mui/base/Portal",
      ],
      [
        "TextareaAutosize",
        "default",
        "@mui/base/TextareaAutosize",
      ],
      [
        "useAutocomplete",
        "default",
        "@mui/base/useAutocomplete",
      ],
      [
        "Accordion",
        "default",
        "@mui/material/Accordion/Accordion.js",
      ],
      [
        "accordionClasses",
        "default",
        "@mui/material/Accordion/accordionClasses.js",
      ],
      [
        "getAccordionUtilityClass",
        "getAccordionUtilityClass",
        "@mui/material/Accordion/accordionClasses.js",
      ],
      [
        "AccordionActions",
        "default",
        "@mui/material/AccordionActions/AccordionActions.js",
      ],
      [
        "accordionActionsClasses",
        "default",
        "@mui/material/AccordionActions/accordionActionsClasses.js",
      ],
      [
        "getAccordionActionsUtilityClass",
        "getAccordionActionsUtilityClass",
        "@mui/material/AccordionActions/accordionActionsClasses.js",
      ],
      [
        "AccordionDetails",
        "default",
        "@mui/material/AccordionDetails/AccordionDetails.js",
      ],
      [
        "accordionDetailsClasses",
        "default",
        "@mui/material/AccordionDetails/accordionDetailsClasses.js",
      ],
      [
        "getAccordionDetailsUtilityClass",
        "getAccordionDetailsUtilityClass",
        "@mui/material/AccordionDetails/accordionDetailsClasses.js",
      ],
      [
        "AccordionSummary",
        "default",
        "@mui/material/AccordionSummary/AccordionSummary.js",
      ],
      [
        "accordionSummaryClasses",
        "default",
        "@mui/material/AccordionSummary/accordionSummaryClasses.js",
      ],
      [
        "getAccordionSummaryUtilityClass",
        "getAccordionSummaryUtilityClass",
        "@mui/material/AccordionSummary/accordionSummaryClasses.js",
      ],
      [
        "Alert",
        "default",
        "@mui/material/Alert/Alert.js",
      ],
      [
        "alertClasses",
        "default",
        "@mui/material/Alert/alertClasses.js",
      ],
      [
        "getAlertUtilityClass",
        "getAlertUtilityClass",
        "@mui/material/Alert/alertClasses.js",
      ],
      [
        "AlertTitle",
        "default",
        "@mui/material/AlertTitle/AlertTitle.js",
      ],
      [
        "alertTitleClasses",
        "default",
        "@mui/material/AlertTitle/alertTitleClasses.js",
      ],
      [
        "getAlertTitleUtilityClass",
        "getAlertTitleUtilityClass",
        "@mui/material/AlertTitle/alertTitleClasses.js",
      ],
      [
        "AppBar",
        "default",
        "@mui/material/AppBar/AppBar.js",
      ],
      [
        "appBarClasses",
        "default",
        "@mui/material/AppBar/appBarClasses.js",
      ],
      [
        "getAppBarUtilityClass",
        "getAppBarUtilityClass",
        "@mui/material/AppBar/appBarClasses.js",
      ],
      [
        "Autocomplete",
        "default",
        "@mui/material/Autocomplete/Autocomplete.js",
      ],
      [
        "createFilterOptions",
        "createFilterOptions",
        "@mui/material/Autocomplete/Autocomplete.js",
      ],
      [
        "autocompleteClasses",
        "default",
        "@mui/material/Autocomplete/autocompleteClasses.js",
      ],
      [
        "getAutocompleteUtilityClass",
        "getAutocompleteUtilityClass",
        "@mui/material/Autocomplete/autocompleteClasses.js",
      ],
      [
        "Avatar",
        "default",
        "@mui/material/Avatar/Avatar.js",
      ],
      [
        "avatarClasses",
        "default",
        "@mui/material/Avatar/avatarClasses.js",
      ],
      [
        "getAvatarUtilityClass",
        "getAvatarUtilityClass",
        "@mui/material/Avatar/avatarClasses.js",
      ],
      [
        "AvatarGroup",
        "default",
        "@mui/material/AvatarGroup/AvatarGroup.js",
      ],
      [
        "avatarGroupClasses",
        "default",
        "@mui/material/AvatarGroup/avatarGroupClasses.js",
      ],
      [
        "getAvatarGroupUtilityClass",
        "getAvatarGroupUtilityClass",
        "@mui/material/AvatarGroup/avatarGroupClasses.js",
      ],
      [
        "Backdrop",
        "default",
        "@mui/material/Backdrop/Backdrop.js",
      ],
      [
        "backdropClasses",
        "default",
        "@mui/material/Backdrop/backdropClasses.js",
      ],
      [
        "getBackdropUtilityClass",
        "getBackdropUtilityClass",
        "@mui/material/Backdrop/backdropClasses.js",
      ],
      [
        "Badge",
        "default",
        "@mui/material/Badge/Badge.js",
      ],
      [
        "badgeClasses",
        "default",
        "@mui/material/Badge/badgeClasses.js",
      ],
      [
        "getBadgeUtilityClass",
        "getBadgeUtilityClass",
        "@mui/material/Badge/badgeClasses.js",
      ],
      [
        "BottomNavigation",
        "default",
        "@mui/material/BottomNavigation/BottomNavigation.js",
      ],
      [
        "bottomNavigationClasses",
        "default",
        "@mui/material/BottomNavigation/bottomNavigationClasses.js",
      ],
      [
        "getBottomNavigationUtilityClass",
        "getBottomNavigationUtilityClass",
        "@mui/material/BottomNavigation/bottomNavigationClasses.js",
      ],
      [
        "BottomNavigationAction",
        "default",
        "@mui/material/BottomNavigationAction/BottomNavigationAction.js",
      ],
      [
        "bottomNavigationActionClasses",
        "default",
        "@mui/material/BottomNavigationAction/bottomNavigationActionClasses.js",
      ],
      [
        "getBottomNavigationActionUtilityClass",
        "getBottomNavigationActionUtilityClass",
        "@mui/material/BottomNavigationAction/bottomNavigationActionClasses.js",
      ],
      [
        "Box",
        "default",
        "@mui/material/Box/Box.js",
      ],
      [
        "Breadcrumbs",
        "default",
        "@mui/material/Breadcrumbs/Breadcrumbs.js",
      ],
      [
        "breadcrumbsClasses",
        "default",
        "@mui/material/Breadcrumbs/breadcrumbsClasses.js",
      ],
      [
        "getBreadcrumbsUtilityClass",
        "getBreadcrumbsUtilityClass",
        "@mui/material/Breadcrumbs/breadcrumbsClasses.js",
      ],
      [
        "Button",
        "default",
        "@mui/material/Button/Button.js",
      ],
      [
        "buttonClasses",
        "default",
        "@mui/material/Button/buttonClasses.js",
      ],
      [
        "getButtonUtilityClass",
        "getButtonUtilityClass",
        "@mui/material/Button/buttonClasses.js",
      ],
      [
        "ButtonBase",
        "default",
        "@mui/material/ButtonBase/ButtonBase.js",
      ],
      [
        "buttonBaseClasses",
        "default",
        "@mui/material/ButtonBase/buttonBaseClasses.js",
      ],
      [
        "getButtonBaseUtilityClass",
        "getButtonBaseUtilityClass",
        "@mui/material/ButtonBase/buttonBaseClasses.js",
      ],
      [
        "touchRippleClasses",
        "default",
        "@mui/material/ButtonBase/touchRippleClasses.js",
      ],
      [
        "getTouchRippleUtilityClass",
        "getTouchRippleUtilityClass",
        "@mui/material/ButtonBase/touchRippleClasses.js",
      ],
      [
        "ButtonGroup",
        "default",
        "@mui/material/ButtonGroup/ButtonGroup.js",
      ],
      [
        "buttonGroupClasses",
        "default",
        "@mui/material/ButtonGroup/buttonGroupClasses.js",
      ],
      [
        "getButtonGroupUtilityClass",
        "getButtonGroupUtilityClass",
        "@mui/material/ButtonGroup/buttonGroupClasses.js",
      ],
      [
        "Card",
        "default",
        "@mui/material/Card/Card.js",
      ],
      [
        "cardClasses",
        "default",
        "@mui/material/Card/cardClasses.js",
      ],
      [
        "getCardUtilityClass",
        "getCardUtilityClass",
        "@mui/material/Card/cardClasses.js",
      ],
      [
        "CardActionArea",
        "default",
        "@mui/material/CardActionArea/CardActionArea.js",
      ],
      [
        "cardActionAreaClasses",
        "default",
        "@mui/material/CardActionArea/cardActionAreaClasses.js",
      ],
      [
        "getCardActionAreaUtilityClass",
        "getCardActionAreaUtilityClass",
        "@mui/material/CardActionArea/cardActionAreaClasses.js",
      ],
      [
        "CardActions",
        "default",
        "@mui/material/CardActions/CardActions.js",
      ],
      [
        "cardActionsClasses",
        "default",
        "@mui/material/CardActions/cardActionsClasses.js",
      ],
      [
        "getCardActionsUtilityClass",
        "getCardActionsUtilityClass",
        "@mui/material/CardActions/cardActionsClasses.js",
      ],
      [
        "CardContent",
        "default",
        "@mui/material/CardContent/CardContent.js",
      ],
      [
        "cardContentClasses",
        "default",
        "@mui/material/CardContent/cardContentClasses.js",
      ],
      [
        "getCardContentUtilityClass",
        "getCardContentUtilityClass",
        "@mui/material/CardContent/cardContentClasses.js",
      ],
      [
        "CardHeader",
        "default",
        "@mui/material/CardHeader/CardHeader.js",
      ],
      [
        "cardHeaderClasses",
        "default",
        "@mui/material/CardHeader/cardHeaderClasses.js",
      ],
      [
        "getCardHeaderUtilityClass",
        "getCardHeaderUtilityClass",
        "@mui/material/CardHeader/cardHeaderClasses.js",
      ],
      [
        "CardMedia",
        "default",
        "@mui/material/CardMedia/CardMedia.js",
      ],
      [
        "cardMediaClasses",
        "default",
        "@mui/material/CardMedia/cardMediaClasses.js",
      ],
      [
        "getCardMediaUtilityClass",
        "getCardMediaUtilityClass",
        "@mui/material/CardMedia/cardMediaClasses.js",
      ],
      [
        "Checkbox",
        "default",
        "@mui/material/Checkbox/Checkbox.js",
      ],
      [
        "checkboxClasses",
        "default",
        "@mui/material/Checkbox/checkboxClasses.js",
      ],
      [
        "getCheckboxUtilityClass",
        "getCheckboxUtilityClass",
        "@mui/material/Checkbox/checkboxClasses.js",
      ],
      [
        "Chip",
        "default",
        "@mui/material/Chip/Chip.js",
      ],
      [
        "chipClasses",
        "default",
        "@mui/material/Chip/chipClasses.js",
      ],
      [
        "getChipUtilityClass",
        "getChipUtilityClass",
        "@mui/material/Chip/chipClasses.js",
      ],
      [
        "CircularProgress",
        "default",
        "@mui/material/CircularProgress/CircularProgress.js",
      ],
      [
        "circularProgressClasses",
        "default",
        "@mui/material/CircularProgress/circularProgressClasses.js",
      ],
      [
        "getCircularProgressUtilityClass",
        "getCircularProgressUtilityClass",
        "@mui/material/CircularProgress/circularProgressClasses.js",
      ],
      [
        "Collapse",
        "default",
        "@mui/material/Collapse/Collapse.js",
      ],
      [
        "collapseClasses",
        "default",
        "@mui/material/Collapse/collapseClasses.js",
      ],
      [
        "getCollapseUtilityClass",
        "getCollapseUtilityClass",
        "@mui/material/Collapse/collapseClasses.js",
      ],
      [
        "colors",
        "*",
        "@mui/material/colors/index.js",
      ],
      [
        "Container",
        "default",
        "@mui/material/Container/Container.js",
      ],
      [
        "containerClasses",
        "default",
        "@mui/material/Container/containerClasses.js",
      ],
      [
        "getContainerUtilityClass",
        "getContainerUtilityClass",
        "@mui/material/Container/containerClasses.js",
      ],
      [
        "CssBaseline",
        "default",
        "@mui/material/CssBaseline/CssBaseline.js",
      ],
      [
        "darkScrollbar",
        "default",
        "@mui/material/darkScrollbar/index.js",
      ],
      [
        "Dialog",
        "default",
        "@mui/material/Dialog/Dialog.js",
      ],
      [
        "dialogClasses",
        "default",
        "@mui/material/Dialog/dialogClasses.js",
      ],
      [
        "getDialogUtilityClass",
        "getDialogUtilityClass",
        "@mui/material/Dialog/dialogClasses.js",
      ],
      [
        "DialogActions",
        "default",
        "@mui/material/DialogActions/DialogActions.js",
      ],
      [
        "dialogActionsClasses",
        "default",
        "@mui/material/DialogActions/dialogActionsClasses.js",
      ],
      [
        "getDialogActionsUtilityClass",
        "getDialogActionsUtilityClass",
        "@mui/material/DialogActions/dialogActionsClasses.js",
      ],
      [
        "DialogContent",
        "default",
        "@mui/material/DialogContent/DialogContent.js",
      ],
      [
        "dialogContentClasses",
        "default",
        "@mui/material/DialogContent/dialogContentClasses.js",
      ],
      [
        "getDialogContentUtilityClass",
        "getDialogContentUtilityClass",
        "@mui/material/DialogContent/dialogContentClasses.js",
      ],
      [
        "DialogContentText",
        "default",
        "@mui/material/DialogContentText/DialogContentText.js",
      ],
      [
        "dialogContentTextClasses",
        "default",
        "@mui/material/DialogContentText/dialogContentTextClasses.js",
      ],
      [
        "getDialogContentTextUtilityClass",
        "getDialogContentTextUtilityClass",
        "@mui/material/DialogContentText/dialogContentTextClasses.js",
      ],
      [
        "DialogTitle",
        "default",
        "@mui/material/DialogTitle/DialogTitle.js",
      ],
      [
        "dialogTitleClasses",
        "default",
        "@mui/material/DialogTitle/dialogTitleClasses.js",
      ],
      [
        "getDialogTitleUtilityClass",
        "getDialogTitleUtilityClass",
        "@mui/material/DialogTitle/dialogTitleClasses.js",
      ],
      [
        "Divider",
        "default",
        "@mui/material/Divider/Divider.js",
      ],
      [
        "dividerClasses",
        "default",
        "@mui/material/Divider/dividerClasses.js",
      ],
      [
        "getDividerUtilityClass",
        "getDividerUtilityClass",
        "@mui/material/Divider/dividerClasses.js",
      ],
      [
        "Drawer",
        "default",
        "@mui/material/Drawer/Drawer.js",
      ],
      [
        "drawerClasses",
        "default",
        "@mui/material/Drawer/drawerClasses.js",
      ],
      [
        "getDrawerUtilityClass",
        "getDrawerUtilityClass",
        "@mui/material/Drawer/drawerClasses.js",
      ],
      [
        "Fab",
        "default",
        "@mui/material/Fab/Fab.js",
      ],
      [
        "fabClasses",
        "default",
        "@mui/material/Fab/fabClasses.js",
      ],
      [
        "getFabUtilityClass",
        "getFabUtilityClass",
        "@mui/material/Fab/fabClasses.js",
      ],
      [
        "Fade",
        "default",
        "@mui/material/Fade/Fade.js",
      ],
      [
        "FilledInput",
        "default",
        "@mui/material/FilledInput/FilledInput.js",
      ],
      [
        "filledInputClasses",
        "default",
        "@mui/material/FilledInput/filledInputClasses.js",
      ],
      [
        "getFilledInputUtilityClass",
        "getFilledInputUtilityClass",
        "@mui/material/FilledInput/filledInputClasses.js",
      ],
      [
        "FormControl",
        "default",
        "@mui/material/FormControl/FormControl.js",
      ],
      [
        "formControlClasses",
        "default",
        "@mui/material/FormControl/formControlClasses.js",
      ],
      [
        "getFormControlUtilityClasses",
        "getFormControlUtilityClasses",
        "@mui/material/FormControl/formControlClasses.js",
      ],
      [
        "useFormControl",
        "default",
        "@mui/material/FormControl/useFormControl.js",
      ],
      [
        "FormControlLabel",
        "default",
        "@mui/material/FormControlLabel/FormControlLabel.js",
      ],
      [
        "formControlLabelClasses",
        "default",
        "@mui/material/FormControlLabel/formControlLabelClasses.js",
      ],
      [
        "getFormControlLabelUtilityClasses",
        "getFormControlLabelUtilityClasses",
        "@mui/material/FormControlLabel/formControlLabelClasses.js",
      ],
      [
        "FormGroup",
        "default",
        "@mui/material/FormGroup/FormGroup.js",
      ],
      [
        "formGroupClasses",
        "default",
        "@mui/material/FormGroup/formGroupClasses.js",
      ],
      [
        "getFormGroupUtilityClass",
        "getFormGroupUtilityClass",
        "@mui/material/FormGroup/formGroupClasses.js",
      ],
      [
        "FormHelperText",
        "default",
        "@mui/material/FormHelperText/FormHelperText.js",
      ],
      [
        "formHelperTextClasses",
        "default",
        "@mui/material/FormHelperText/formHelperTextClasses.js",
      ],
      [
        "getFormHelperTextUtilityClasses",
        "getFormHelperTextUtilityClasses",
        "@mui/material/FormHelperText/formHelperTextClasses.js",
      ],
      [
        "FormLabel",
        "default",
        "@mui/material/FormLabel/FormLabel.js",
      ],
      [
        "FormLabelRoot",
        "FormLabelRoot",
        "@mui/material/FormLabel/FormLabel.js",
      ],
      [
        "formLabelClasses",
        "default",
        "@mui/material/FormLabel/formLabelClasses.js",
      ],
      [
        "getFormLabelUtilityClasses",
        "getFormLabelUtilityClasses",
        "@mui/material/FormLabel/formLabelClasses.js",
      ],
      [
        "GlobalStyles",
        "default",
        "@mui/material/GlobalStyles/GlobalStyles.js",
      ],
      [
        "Grid",
        "default",
        "@mui/material/Grid/Grid.js",
      ],
      [
        "gridClasses",
        "default",
        "@mui/material/Grid/gridClasses.js",
      ],
      [
        "getGridUtilityClass",
        "getGridUtilityClass",
        "@mui/material/Grid/gridClasses.js",
      ],
      [
        "Grow",
        "default",
        "@mui/material/Grow/Grow.js",
      ],
      [
        "Hidden",
        "default",
        "@mui/material/Hidden/Hidden.js",
      ],
      [
        "Icon",
        "default",
        "@mui/material/Icon/Icon.js",
      ],
      [
        "iconClasses",
        "default",
        "@mui/material/Icon/iconClasses.js",
      ],
      [
        "getIconUtilityClass",
        "getIconUtilityClass",
        "@mui/material/Icon/iconClasses.js",
      ],
      [
        "IconButton",
        "default",
        "@mui/material/IconButton/IconButton.js",
      ],
      [
        "iconButtonClasses",
        "default",
        "@mui/material/IconButton/iconButtonClasses.js",
      ],
      [
        "getIconButtonUtilityClass",
        "getIconButtonUtilityClass",
        "@mui/material/IconButton/iconButtonClasses.js",
      ],
      [
        "ImageList",
        "default",
        "@mui/material/ImageList/ImageList.js",
      ],
      [
        "getImageListUtilityClass",
        "getImageListUtilityClass",
        "@mui/material/ImageList/imageListClasses.js",
      ],
      [
        "imageListClasses",
        "default",
        "@mui/material/ImageList/imageListClasses.js",
      ],
      [
        "ImageListItem",
        "default",
        "@mui/material/ImageListItem/ImageListItem.js",
      ],
      [
        "getImageListItemUtilityClass",
        "getImageListItemUtilityClass",
        "@mui/material/ImageListItem/imageListItemClasses.js",
      ],
      [
        "imageListItemClasses",
        "default",
        "@mui/material/ImageListItem/imageListItemClasses.js",
      ],
      [
        "ImageListItemBar",
        "default",
        "@mui/material/ImageListItemBar/ImageListItemBar.js",
      ],
      [
        "getImageListItemBarUtilityClass",
        "getImageListItemBarUtilityClass",
        "@mui/material/ImageListItemBar/imageListItemBarClasses.js",
      ],
      [
        "imageListItemBarClasses",
        "default",
        "@mui/material/ImageListItemBar/imageListItemBarClasses.js",
      ],
      [
        "Input",
        "default",
        "@mui/material/Input/Input.js",
      ],
      [
        "inputClasses",
        "default",
        "@mui/material/Input/inputClasses.js",
      ],
      [
        "getInputUtilityClass",
        "getInputUtilityClass",
        "@mui/material/Input/inputClasses.js",
      ],
      [
        "InputAdornment",
        "default",
        "@mui/material/InputAdornment/InputAdornment.js",
      ],
      [
        "inputAdornmentClasses",
        "default",
        "@mui/material/InputAdornment/inputAdornmentClasses.js",
      ],
      [
        "getInputAdornmentUtilityClass",
        "getInputAdornmentUtilityClass",
        "@mui/material/InputAdornment/inputAdornmentClasses.js",
      ],
      [
        "InputBase",
        "default",
        "@mui/material/InputBase/InputBase.js",
      ],
      [
        "inputBaseClasses",
        "default",
        "@mui/material/InputBase/inputBaseClasses.js",
      ],
      [
        "getInputBaseUtilityClass",
        "getInputBaseUtilityClass",
        "@mui/material/InputBase/inputBaseClasses.js",
      ],
      [
        "InputLabel",
        "default",
        "@mui/material/InputLabel/InputLabel.js",
      ],
      [
        "inputLabelClasses",
        "default",
        "@mui/material/InputLabel/inputLabelClasses.js",
      ],
      [
        "getInputLabelUtilityClasses",
        "getInputLabelUtilityClasses",
        "@mui/material/InputLabel/inputLabelClasses.js",
      ],
      [
        "LinearProgress",
        "default",
        "@mui/material/LinearProgress/LinearProgress.js",
      ],
      [
        "linearProgressClasses",
        "default",
        "@mui/material/LinearProgress/linearProgressClasses.js",
      ],
      [
        "getLinearProgressUtilityClass",
        "getLinearProgressUtilityClass",
        "@mui/material/LinearProgress/linearProgressClasses.js",
      ],
      [
        "Link",
        "default",
        "@mui/material/Link/Link.js",
      ],
      [
        "linkClasses",
        "default",
        "@mui/material/Link/linkClasses.js",
      ],
      [
        "getLinkUtilityClass",
        "getLinkUtilityClass",
        "@mui/material/Link/linkClasses.js",
      ],
      [
        "List",
        "default",
        "@mui/material/List/List.js",
      ],
      [
        "listClasses",
        "default",
        "@mui/material/List/listClasses.js",
      ],
      [
        "getListUtilityClass",
        "getListUtilityClass",
        "@mui/material/List/listClasses.js",
      ],
      [
        "ListItem",
        "default",
        "@mui/material/ListItem/ListItem.js",
      ],
      [
        "listItemClasses",
        "default",
        "@mui/material/ListItem/listItemClasses.js",
      ],
      [
        "getListItemUtilityClass",
        "getListItemUtilityClass",
        "@mui/material/ListItem/listItemClasses.js",
      ],
      [
        "ListItemAvatar",
        "default",
        "@mui/material/ListItemAvatar/ListItemAvatar.js",
      ],
      [
        "listItemAvatarClasses",
        "default",
        "@mui/material/ListItemAvatar/listItemAvatarClasses.js",
      ],
      [
        "getListItemAvatarUtilityClass",
        "getListItemAvatarUtilityClass",
        "@mui/material/ListItemAvatar/listItemAvatarClasses.js",
      ],
      [
        "ListItemButton",
        "default",
        "@mui/material/ListItemButton/ListItemButton.js",
      ],
      [
        "listItemButtonClasses",
        "default",
        "@mui/material/ListItemButton/listItemButtonClasses.js",
      ],
      [
        "getListItemButtonUtilityClass",
        "getListItemButtonUtilityClass",
        "@mui/material/ListItemButton/listItemButtonClasses.js",
      ],
      [
        "ListItemIcon",
        "default",
        "@mui/material/ListItemIcon/ListItemIcon.js",
      ],
      [
        "listItemIconClasses",
        "default",
        "@mui/material/ListItemIcon/listItemIconClasses.js",
      ],
      [
        "getListItemIconUtilityClass",
        "getListItemIconUtilityClass",
        "@mui/material/ListItemIcon/listItemIconClasses.js",
      ],
      [
        "ListItemSecondaryAction",
        "default",
        "@mui/material/ListItemSecondaryAction/ListItemSecondaryAction.js",
      ],
      [
        "listItemSecondaryActionClasses",
        "default",
        "@mui/material/ListItemSecondaryAction/listItemSecondaryActionClasses.js",
      ],
      [
        "getListItemSecondaryActionClassesUtilityClass",
        "getListItemSecondaryActionClassesUtilityClass",
        "@mui/material/ListItemSecondaryAction/listItemSecondaryActionClasses.js",
      ],
      [
        "ListItemText",
        "default",
        "@mui/material/ListItemText/ListItemText.js",
      ],
      [
        "listItemTextClasses",
        "default",
        "@mui/material/ListItemText/listItemTextClasses.js",
      ],
      [
        "getListItemTextUtilityClass",
        "getListItemTextUtilityClass",
        "@mui/material/ListItemText/listItemTextClasses.js",
      ],
      [
        "ListSubheader",
        "default",
        "@mui/material/ListSubheader/ListSubheader.js",
      ],
      [
        "listSubheaderClasses",
        "default",
        "@mui/material/ListSubheader/listSubheaderClasses.js",
      ],
      [
        "getListSubheaderUtilityClass",
        "getListSubheaderUtilityClass",
        "@mui/material/ListSubheader/listSubheaderClasses.js",
      ],
      [
        "Menu",
        "default",
        "@mui/material/Menu/Menu.js",
      ],
      [
        "menuClasses",
        "default",
        "@mui/material/Menu/menuClasses.js",
      ],
      [
        "getMenuUtilityClass",
        "getMenuUtilityClass",
        "@mui/material/Menu/menuClasses.js",
      ],
      [
        "MenuItem",
        "default",
        "@mui/material/MenuItem/MenuItem.js",
      ],
      [
        "getMenuItemUtilityClass",
        "getMenuItemUtilityClass",
        "@mui/material/MenuItem/menuItemClasses.js",
      ],
      [
        "menuItemClasses",
        "default",
        "@mui/material/MenuItem/menuItemClasses.js",
      ],
      [
        "MenuList",
        "default",
        "@mui/material/MenuList/MenuList.js",
      ],
      [
        "MobileStepper",
        "default",
        "@mui/material/MobileStepper/MobileStepper.js",
      ],
      [
        "mobileStepperClasses",
        "default",
        "@mui/material/MobileStepper/mobileStepperClasses.js",
      ],
      [
        "getMobileStepperUtilityClass",
        "getMobileStepperUtilityClass",
        "@mui/material/MobileStepper/mobileStepperClasses.js",
      ],
      [
        "Modal",
        "default",
        "@mui/material/Modal/Modal.js",
      ],
      [
        "modalClasses",
        "modalClasses",
        "@mui/material/Modal/Modal.js",
      ],
      [
        "NativeSelect",
        "default",
        "@mui/material/NativeSelect/NativeSelect.js",
      ],
      [
        "nativeSelectClasses",
        "default",
        "@mui/material/NativeSelect/nativeSelectClasses.js",
      ],
      [
        "getNativeSelectUtilityClasses",
        "getNativeSelectUtilityClasses",
        "@mui/material/NativeSelect/nativeSelectClasses.js",
      ],
      [
        "OutlinedInput",
        "default",
        "@mui/material/OutlinedInput/OutlinedInput.js",
      ],
      [
        "outlinedInputClasses",
        "default",
        "@mui/material/OutlinedInput/outlinedInputClasses.js",
      ],
      [
        "getOutlinedInputUtilityClass",
        "getOutlinedInputUtilityClass",
        "@mui/material/OutlinedInput/outlinedInputClasses.js",
      ],
      [
        "Pagination",
        "default",
        "@mui/material/Pagination/Pagination.js",
      ],
      [
        "paginationClasses",
        "default",
        "@mui/material/Pagination/paginationClasses.js",
      ],
      [
        "getPaginationUtilityClass",
        "getPaginationUtilityClass",
        "@mui/material/Pagination/paginationClasses.js",
      ],
      [
        "PaginationItem",
        "default",
        "@mui/material/PaginationItem/PaginationItem.js",
      ],
      [
        "paginationItemClasses",
        "default",
        "@mui/material/PaginationItem/paginationItemClasses.js",
      ],
      [
        "getPaginationItemUtilityClass",
        "getPaginationItemUtilityClass",
        "@mui/material/PaginationItem/paginationItemClasses.js",
      ],
      [
        "Paper",
        "default",
        "@mui/material/Paper/Paper.js",
      ],
      [
        "paperClasses",
        "default",
        "@mui/material/Paper/paperClasses.js",
      ],
      [
        "getPaperUtilityClass",
        "getPaperUtilityClass",
        "@mui/material/Paper/paperClasses.js",
      ],
      [
        "Popover",
        "default",
        "@mui/material/Popover/Popover.js",
      ],
      [
        "getOffsetTop",
        "getOffsetTop",
        "@mui/material/Popover/Popover.js",
      ],
      [
        "getOffsetLeft",
        "getOffsetLeft",
        "@mui/material/Popover/Popover.js",
      ],
      [
        "popoverClasses",
        "default",
        "@mui/material/Popover/popoverClasses.js",
      ],
      [
        "getPopoverUtilityClass",
        "getPopoverUtilityClass",
        "@mui/material/Popover/popoverClasses.js",
      ],
      [
        "Popper",
        "default",
        "@mui/material/Popper/Popper.js",
      ],
      [
        "Radio",
        "default",
        "@mui/material/Radio/Radio.js",
      ],
      [
        "radioClasses",
        "default",
        "@mui/material/Radio/radioClasses.js",
      ],
      [
        "getRadioUtilityClass",
        "getRadioUtilityClass",
        "@mui/material/Radio/radioClasses.js",
      ],
      [
        "RadioGroup",
        "default",
        "@mui/material/RadioGroup/RadioGroup.js",
      ],
      [
        "useRadioGroup",
        "default",
        "@mui/material/RadioGroup/useRadioGroup.js",
      ],
      [
        "Rating",
        "default",
        "@mui/material/Rating/Rating.js",
      ],
      [
        "ratingClasses",
        "default",
        "@mui/material/Rating/ratingClasses.js",
      ],
      [
        "getRatingUtilityClass",
        "getRatingUtilityClass",
        "@mui/material/Rating/ratingClasses.js",
      ],
      [
        "ScopedCssBaseline",
        "default",
        "@mui/material/ScopedCssBaseline/ScopedCssBaseline.js",
      ],
      [
        "scopedCssBaselineClasses",
        "default",
        "@mui/material/ScopedCssBaseline/scopedCssBaselineClasses.js",
      ],
      [
        "getScopedCssBaselineUtilityClass",
        "getScopedCssBaselineUtilityClass",
        "@mui/material/ScopedCssBaseline/scopedCssBaselineClasses.js",
      ],
      [
        "Select",
        "default",
        "@mui/material/Select/Select.js",
      ],
      [
        "selectClasses",
        "default",
        "@mui/material/Select/selectClasses.js",
      ],
      [
        "getSelectUtilityClasses",
        "getSelectUtilityClasses",
        "@mui/material/Select/selectClasses.js",
      ],
      [
        "Skeleton",
        "default",
        "@mui/material/Skeleton/Skeleton.js",
      ],
      [
        "getSkeletonUtilityClass",
        "getSkeletonUtilityClass",
        "@mui/material/Skeleton/skeletonClasses.js",
      ],
      [
        "skeletonClasses",
        "default",
        "@mui/material/Skeleton/skeletonClasses.js",
      ],
      [
        "Slide",
        "default",
        "@mui/material/Slide/Slide.js",
      ],
      [
        "Slider",
        "default",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "SliderRoot",
        "SliderRoot",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "SliderRail",
        "SliderRail",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "SliderTrack",
        "SliderTrack",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "SliderThumb",
        "SliderThumb",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "SliderValueLabel",
        "StyledSliderValueLabel",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "SliderMark",
        "SliderMark",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "SliderMarkLabel",
        "SliderMarkLabel",
        "@mui/material/Slider/Slider.js",
      ],
      [
        "sliderClasses",
        "default",
        "@mui/material/Slider/sliderClasses.js",
      ],
      [
        "getSliderUtilityClass",
        "getSliderUtilityClass",
        "@mui/material/Slider/sliderClasses.js",
      ],
      [
        "Snackbar",
        "default",
        "@mui/material/Snackbar/Snackbar.js",
      ],
      [
        "snackbarClasses",
        "default",
        "@mui/material/Snackbar/snackbarClasses.js",
      ],
      [
        "getSnackbarUtilityClass",
        "getSnackbarUtilityClass",
        "@mui/material/Snackbar/snackbarClasses.js",
      ],
      [
        "SnackbarContent",
        "default",
        "@mui/material/SnackbarContent/SnackbarContent.js",
      ],
      [
        "snackbarContentClasses",
        "default",
        "@mui/material/SnackbarContent/snackbarContentClasses.js",
      ],
      [
        "getSnackbarContentUtilityClass",
        "getSnackbarContentUtilityClass",
        "@mui/material/SnackbarContent/snackbarContentClasses.js",
      ],
      [
        "SpeedDial",
        "default",
        "@mui/material/SpeedDial/SpeedDial.js",
      ],
      [
        "speedDialClasses",
        "default",
        "@mui/material/SpeedDial/speedDialClasses.js",
      ],
      [
        "getSpeedDialUtilityClass",
        "getSpeedDialUtilityClass",
        "@mui/material/SpeedDial/speedDialClasses.js",
      ],
      [
        "SpeedDialAction",
        "default",
        "@mui/material/SpeedDialAction/SpeedDialAction.js",
      ],
      [
        "speedDialActionClasses",
        "default",
        "@mui/material/SpeedDialAction/speedDialActionClasses.js",
      ],
      [
        "getSpeedDialActionUtilityClass",
        "getSpeedDialActionUtilityClass",
        "@mui/material/SpeedDialAction/speedDialActionClasses.js",
      ],
      [
        "SpeedDialIcon",
        "default",
        "@mui/material/SpeedDialIcon/SpeedDialIcon.js",
      ],
      [
        "speedDialIconClasses",
        "default",
        "@mui/material/SpeedDialIcon/speedDialIconClasses.js",
      ],
      [
        "getSpeedDialIconUtilityClass",
        "getSpeedDialIconUtilityClass",
        "@mui/material/SpeedDialIcon/speedDialIconClasses.js",
      ],
      [
        "Stack",
        "default",
        "@mui/material/Stack/Stack.js",
      ],
      [
        "stackClasses",
        "default",
        "@mui/material/Stack/stackClasses.js",
      ],
      [
        "Step",
        "default",
        "@mui/material/Step/Step.js",
      ],
      [
        "stepClasses",
        "default",
        "@mui/material/Step/stepClasses.js",
      ],
      [
        "getStepUtilityClass",
        "getStepUtilityClass",
        "@mui/material/Step/stepClasses.js",
      ],
      [
        "StepContext",
        "default",
        "@mui/material/Step/StepContext.js",
      ],
      [
        "useStepContext",
        "useStepContext",
        "@mui/material/Step/StepContext.js",
      ],
      [
        "StepButton",
        "default",
        "@mui/material/StepButton/StepButton.js",
      ],
      [
        "stepButtonClasses",
        "default",
        "@mui/material/StepButton/stepButtonClasses.js",
      ],
      [
        "getStepButtonUtilityClass",
        "getStepButtonUtilityClass",
        "@mui/material/StepButton/stepButtonClasses.js",
      ],
      [
        "StepConnector",
        "default",
        "@mui/material/StepConnector/StepConnector.js",
      ],
      [
        "stepConnectorClasses",
        "default",
        "@mui/material/StepConnector/stepConnectorClasses.js",
      ],
      [
        "getStepConnectorUtilityClass",
        "getStepConnectorUtilityClass",
        "@mui/material/StepConnector/stepConnectorClasses.js",
      ],
      [
        "StepContent",
        "default",
        "@mui/material/StepContent/StepContent.js",
      ],
      [
        "stepContentClasses",
        "default",
        "@mui/material/StepContent/stepContentClasses.js",
      ],
      [
        "getStepContentUtilityClass",
        "getStepContentUtilityClass",
        "@mui/material/StepContent/stepContentClasses.js",
      ],
      [
        "StepIcon",
        "default",
        "@mui/material/StepIcon/StepIcon.js",
      ],
      [
        "stepIconClasses",
        "default",
        "@mui/material/StepIcon/stepIconClasses.js",
      ],
      [
        "getStepIconUtilityClass",
        "getStepIconUtilityClass",
        "@mui/material/StepIcon/stepIconClasses.js",
      ],
      [
        "StepLabel",
        "default",
        "@mui/material/StepLabel/StepLabel.js",
      ],
      [
        "stepLabelClasses",
        "default",
        "@mui/material/StepLabel/stepLabelClasses.js",
      ],
      [
        "getStepLabelUtilityClass",
        "getStepLabelUtilityClass",
        "@mui/material/StepLabel/stepLabelClasses.js",
      ],
      [
        "Stepper",
        "default",
        "@mui/material/Stepper/Stepper.js",
      ],
      [
        "stepperClasses",
        "default",
        "@mui/material/Stepper/stepperClasses.js",
      ],
      [
        "getStepperUtilityClass",
        "getStepperUtilityClass",
        "@mui/material/Stepper/stepperClasses.js",
      ],
      [
        "StepperContext",
        "default",
        "@mui/material/Stepper/StepperContext.js",
      ],
      [
        "useStepperContext",
        "useStepperContext",
        "@mui/material/Stepper/StepperContext.js",
      ],
      [
        "adaptV4Theme",
        "default",
        "@mui/material/styles/adaptV4Theme.js",
      ],
      [
        "unstable_createMuiStrictModeTheme",
        "default",
        "@mui/material/styles/createMuiStrictModeTheme.js",
      ],
      [
        "createStyles",
        "default",
        "@mui/material/styles/createStyles.js",
      ],
      [
        "createMuiTheme",
        "createMuiTheme",
        "@mui/material/styles/createTheme.js",
      ],
      [
        "createTheme",
        "default",
        "@mui/material/styles/createTheme.js",
      ],
      [
        "easing",
        "easing",
        "@mui/material/styles/createTransitions.js",
      ],
      [
        "duration",
        "duration",
        "@mui/material/styles/createTransitions.js",
      ],
      [
        "private_createTypography",
        "default",
        "@mui/material/styles/createTypography.js",
      ],
      [
        "unstable_getUnit",
        "getUnit",
        "@mui/material/styles/cssUtils.js",
      ],
      [
        "unstable_toUnitless",
        "toUnitless",
        "@mui/material/styles/cssUtils.js",
      ],
      [
        "useColorScheme",
        "useColorScheme",
        "@mui/material/styles/CssVarsProvider.js",
      ],
      [
        "getInitColorSchemeScript",
        "getInitColorSchemeScript",
        "@mui/material/styles/CssVarsProvider.js",
      ],
      [
        "shouldSkipGeneratingVar",
        "shouldSkipGeneratingVar",
        "@mui/material/styles/CssVarsProvider.js",
      ],
      [
        "Experimental_CssVarsProvider",
        "CssVarsProvider",
        "@mui/material/styles/CssVarsProvider.js",
      ],
      [
        "private_excludeVariablesFromRoot",
        "default",
        "@mui/material/styles/excludeVariablesFromRoot.js",
      ],
      [
        "experimental_extendTheme",
        "default",
        "@mui/material/styles/experimental_extendTheme.js",
      ],
      [
        "getOverlayAlpha",
        "default",
        "@mui/material/styles/getOverlayAlpha.js",
      ],
      [
        "experimental_sx",
        "experimental_sx",
        "@mui/material/styles/index.js",
      ],
      [
        "makeStyles",
        "default",
        "@mui/material/styles/makeStyles.js",
      ],
      [
        "responsiveFontSizes",
        "default",
        "@mui/material/styles/responsiveFontSizes.js",
      ],
      [
        "styled",
        "default",
        "@mui/material/styles/styled.js",
      ],
      [
        "experimentalStyled",
        "default",
        "@mui/material/styles/styled.js",
      ],
      [
        "useTheme",
        "default",
        "@mui/material/styles/useTheme.js",
      ],
      [
        "useThemeProps",
        "default",
        "@mui/material/styles/useThemeProps.js",
      ],
      [
        "withStyles",
        "default",
        "@mui/material/styles/withStyles.js",
      ],
      [
        "withTheme",
        "default",
        "@mui/material/styles/withTheme.js",
      ],
      [
        "SvgIcon",
        "default",
        "@mui/material/SvgIcon/SvgIcon.js",
      ],
      [
        "svgIconClasses",
        "default",
        "@mui/material/SvgIcon/svgIconClasses.js",
      ],
      [
        "getSvgIconUtilityClass",
        "getSvgIconUtilityClass",
        "@mui/material/SvgIcon/svgIconClasses.js",
      ],
      [
        "SwipeableDrawer",
        "default",
        "@mui/material/SwipeableDrawer/SwipeableDrawer.js",
      ],
      [
        "Switch",
        "default",
        "@mui/material/Switch/Switch.js",
      ],
      [
        "switchClasses",
        "default",
        "@mui/material/Switch/switchClasses.js",
      ],
      [
        "getSwitchUtilityClass",
        "getSwitchUtilityClass",
        "@mui/material/Switch/switchClasses.js",
      ],
      [
        "Tab",
        "default",
        "@mui/material/Tab/Tab.js",
      ],
      [
        "tabClasses",
        "default",
        "@mui/material/Tab/tabClasses.js",
      ],
      [
        "getTabUtilityClass",
        "getTabUtilityClass",
        "@mui/material/Tab/tabClasses.js",
      ],
      [
        "Table",
        "default",
        "@mui/material/Table/Table.js",
      ],
      [
        "tableClasses",
        "default",
        "@mui/material/Table/tableClasses.js",
      ],
      [
        "getTableUtilityClass",
        "getTableUtilityClass",
        "@mui/material/Table/tableClasses.js",
      ],
      [
        "TableBody",
        "default",
        "@mui/material/TableBody/TableBody.js",
      ],
      [
        "tableBodyClasses",
        "default",
        "@mui/material/TableBody/tableBodyClasses.js",
      ],
      [
        "getTableBodyUtilityClass",
        "getTableBodyUtilityClass",
        "@mui/material/TableBody/tableBodyClasses.js",
      ],
      [
        "TableCell",
        "default",
        "@mui/material/TableCell/TableCell.js",
      ],
      [
        "tableCellClasses",
        "default",
        "@mui/material/TableCell/tableCellClasses.js",
      ],
      [
        "getTableCellUtilityClass",
        "getTableCellUtilityClass",
        "@mui/material/TableCell/tableCellClasses.js",
      ],
      [
        "TableContainer",
        "default",
        "@mui/material/TableContainer/TableContainer.js",
      ],
      [
        "tableContainerClasses",
        "default",
        "@mui/material/TableContainer/tableContainerClasses.js",
      ],
      [
        "getTableContainerUtilityClass",
        "getTableContainerUtilityClass",
        "@mui/material/TableContainer/tableContainerClasses.js",
      ],
      [
        "TableFooter",
        "default",
        "@mui/material/TableFooter/TableFooter.js",
      ],
      [
        "tableFooterClasses",
        "default",
        "@mui/material/TableFooter/tableFooterClasses.js",
      ],
      [
        "getTableFooterUtilityClass",
        "getTableFooterUtilityClass",
        "@mui/material/TableFooter/tableFooterClasses.js",
      ],
      [
        "TableHead",
        "default",
        "@mui/material/TableHead/TableHead.js",
      ],
      [
        "tableHeadClasses",
        "default",
        "@mui/material/TableHead/tableHeadClasses.js",
      ],
      [
        "getTableHeadUtilityClass",
        "getTableHeadUtilityClass",
        "@mui/material/TableHead/tableHeadClasses.js",
      ],
      [
        "TablePagination",
        "default",
        "@mui/material/TablePagination/TablePagination.js",
      ],
      [
        "tablePaginationClasses",
        "default",
        "@mui/material/TablePagination/tablePaginationClasses.js",
      ],
      [
        "getTablePaginationUtilityClass",
        "getTablePaginationUtilityClass",
        "@mui/material/TablePagination/tablePaginationClasses.js",
      ],
      [
        "TableRow",
        "default",
        "@mui/material/TableRow/TableRow.js",
      ],
      [
        "tableRowClasses",
        "default",
        "@mui/material/TableRow/tableRowClasses.js",
      ],
      [
        "getTableRowUtilityClass",
        "getTableRowUtilityClass",
        "@mui/material/TableRow/tableRowClasses.js",
      ],
      [
        "TableSortLabel",
        "default",
        "@mui/material/TableSortLabel/TableSortLabel.js",
      ],
      [
        "tableSortLabelClasses",
        "default",
        "@mui/material/TableSortLabel/tableSortLabelClasses.js",
      ],
      [
        "getTableSortLabelUtilityClass",
        "getTableSortLabelUtilityClass",
        "@mui/material/TableSortLabel/tableSortLabelClasses.js",
      ],
      [
        "Tabs",
        "default",
        "@mui/material/Tabs/Tabs.js",
      ],
      [
        "tabsClasses",
        "default",
        "@mui/material/Tabs/tabsClasses.js",
      ],
      [
        "getTabsUtilityClass",
        "getTabsUtilityClass",
        "@mui/material/Tabs/tabsClasses.js",
      ],
      [
        "TabScrollButton",
        "default",
        "@mui/material/TabScrollButton/TabScrollButton.js",
      ],
      [
        "tabScrollButtonClasses",
        "default",
        "@mui/material/TabScrollButton/tabScrollButtonClasses.js",
      ],
      [
        "getTabScrollButtonUtilityClass",
        "getTabScrollButtonUtilityClass",
        "@mui/material/TabScrollButton/tabScrollButtonClasses.js",
      ],
      [
        "TextField",
        "default",
        "@mui/material/TextField/TextField.js",
      ],
      [
        "textFieldClasses",
        "default",
        "@mui/material/TextField/textFieldClasses.js",
      ],
      [
        "getTextFieldUtilityClass",
        "getTextFieldUtilityClass",
        "@mui/material/TextField/textFieldClasses.js",
      ],
      [
        "ToggleButton",
        "default",
        "@mui/material/ToggleButton/ToggleButton.js",
      ],
      [
        "toggleButtonClasses",
        "default",
        "@mui/material/ToggleButton/toggleButtonClasses.js",
      ],
      [
        "getToggleButtonUtilityClass",
        "getToggleButtonUtilityClass",
        "@mui/material/ToggleButton/toggleButtonClasses.js",
      ],
      [
        "ToggleButtonGroup",
        "default",
        "@mui/material/ToggleButtonGroup/ToggleButtonGroup.js",
      ],
      [
        "toggleButtonGroupClasses",
        "default",
        "@mui/material/ToggleButtonGroup/toggleButtonGroupClasses.js",
      ],
      [
        "getToggleButtonGroupUtilityClass",
        "getToggleButtonGroupUtilityClass",
        "@mui/material/ToggleButtonGroup/toggleButtonGroupClasses.js",
      ],
      [
        "Toolbar",
        "default",
        "@mui/material/Toolbar/Toolbar.js",
      ],
      [
        "toolbarClasses",
        "default",
        "@mui/material/Toolbar/toolbarClasses.js",
      ],
      [
        "getToolbarUtilityClass",
        "getToolbarUtilityClass",
        "@mui/material/Toolbar/toolbarClasses.js",
      ],
      [
        "Tooltip",
        "default",
        "@mui/material/Tooltip/Tooltip.js",
      ],
      [
        "tooltipClasses",
        "default",
        "@mui/material/Tooltip/tooltipClasses.js",
      ],
      [
        "getTooltipUtilityClass",
        "getTooltipUtilityClass",
        "@mui/material/Tooltip/tooltipClasses.js",
      ],
      [
        "Typography",
        "default",
        "@mui/material/Typography/Typography.js",
      ],
      [
        "typographyClasses",
        "default",
        "@mui/material/Typography/typographyClasses.js",
      ],
      [
        "getTypographyUtilityClass",
        "getTypographyUtilityClass",
        "@mui/material/Typography/typographyClasses.js",
      ],
      [
        "Unstable_Grid2",
        "default",
        "@mui/material/Unstable_Grid2/Grid2.js",
      ],
      [
        "grid2Classes",
        "default",
        "@mui/material/Unstable_Grid2/grid2Classes.js",
      ],
      [
        "getGrid2UtilityClass",
        "getGrid2UtilityClass",
        "@mui/material/Unstable_Grid2/grid2Classes.js",
      ],
      [
        "useMediaQuery",
        "default",
        "@mui/material/useMediaQuery/useMediaQuery.js",
      ],
      [
        "usePagination",
        "default",
        "@mui/material/usePagination/usePagination.js",
      ],
      [
        "useScrollTrigger",
        "default",
        "@mui/material/useScrollTrigger/useScrollTrigger.js",
      ],
      [
        "capitalize",
        "default",
        "@mui/material/utils/capitalize.js",
      ],
      [
        "createChainedFunction",
        "default",
        "@mui/material/utils/createChainedFunction.js",
      ],
      [
        "createSvgIcon",
        "default",
        "@mui/material/utils/createSvgIcon.js",
      ],
      [
        "debounce",
        "default",
        "@mui/material/utils/debounce.js",
      ],
      [
        "deprecatedPropType",
        "default",
        "@mui/material/utils/deprecatedPropType.js",
      ],
      [
        "unstable_ClassNameGenerator",
        "unstable_ClassNameGenerator",
        "@mui/material/utils/index.js",
      ],
      [
        "isMuiElement",
        "default",
        "@mui/material/utils/isMuiElement.js",
      ],
      [
        "ownerDocument",
        "default",
        "@mui/material/utils/ownerDocument.js",
      ],
      [
        "ownerWindow",
        "default",
        "@mui/material/utils/ownerWindow.js",
      ],
      [
        "requirePropFactory",
        "default",
        "@mui/material/utils/requirePropFactory.js",
      ],
      [
        "setRef",
        "default",
        "@mui/material/utils/setRef.js",
      ],
      [
        "unsupportedProp",
        "default",
        "@mui/material/utils/unsupportedProp.js",
      ],
      [
        "useControlled",
        "default",
        "@mui/material/utils/useControlled.js",
      ],
      [
        "unstable_useEnhancedEffect",
        "default",
        "@mui/material/utils/useEnhancedEffect.js",
      ],
      [
        "useEventCallback",
        "default",
        "@mui/material/utils/useEventCallback.js",
      ],
      [
        "useForkRef",
        "default",
        "@mui/material/utils/useForkRef.js",
      ],
      [
        "unstable_useId",
        "default",
        "@mui/material/utils/useId.js",
      ],
      [
        "useIsFocusVisible",
        "default",
        "@mui/material/utils/useIsFocusVisible.js",
      ],
      [
        "Zoom",
        "default",
        "@mui/material/Zoom/Zoom.js",
      ],
      [
        "hexToRgb",
        "hexToRgb",
        "@mui/system",
      ],
      [
        "rgbToHex",
        "rgbToHex",
        "@mui/system",
      ],
      [
        "hslToRgb",
        "hslToRgb",
        "@mui/system",
      ],
      [
        "decomposeColor",
        "decomposeColor",
        "@mui/system",
      ],
      [
        "recomposeColor",
        "recomposeColor",
        "@mui/system",
      ],
      [
        "getContrastRatio",
        "getContrastRatio",
        "@mui/system",
      ],
      [
        "getLuminance",
        "getLuminance",
        "@mui/system",
      ],
      [
        "emphasize",
        "emphasize",
        "@mui/system",
      ],
      [
        "alpha",
        "alpha",
        "@mui/system",
      ],
      [
        "darken",
        "darken",
        "@mui/system",
      ],
      [
        "lighten",
        "lighten",
        "@mui/system",
      ],
      [
        "css",
        "css",
        "@mui/system",
      ],
      [
        "keyframes",
        "keyframes",
        "@mui/system",
      ],
      [
        "ThemeProvider",
        "ThemeProvider",
        "@mui/system",
      ],
      [
        "StyledEngineProvider",
        "StyledEngineProvider",
        "@mui/system",
      ],
      [
        "generateUtilityClass",
        "unstable_generateUtilityClass",
        "@mui/utils",
      ],
      [
        "generateUtilityClasses",
        "unstable_generateUtilityClasses",
        "@mui/utils",
      ],
    ]
  `);
});
