import { expect, test } from "vitest";
import { testExports } from "../../utils.js";

test("exports", () => {
  expect(testExports("@mui/system")).toMatchInlineSnapshot(`
    [
      [
        "css",
        "css",
        "@mui/styled-engine",
      ],
      [
        "keyframes",
        "keyframes",
        "@mui/styled-engine",
      ],
      [
        "GlobalStyles",
        "GlobalStyles",
        "@mui/styled-engine",
      ],
      [
        "StyledEngineProvider",
        "StyledEngineProvider",
        "@mui/styled-engine",
      ],
      [
        "borders",
        "default",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderTransform",
        "borderTransform",
        "@mui/system/esm/borders.js",
      ],
      [
        "border",
        "border",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderTop",
        "borderTop",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderRight",
        "borderRight",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderBottom",
        "borderBottom",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderLeft",
        "borderLeft",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderColor",
        "borderColor",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderTopColor",
        "borderTopColor",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderRightColor",
        "borderRightColor",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderBottomColor",
        "borderBottomColor",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderLeftColor",
        "borderLeftColor",
        "@mui/system/esm/borders.js",
      ],
      [
        "borderRadius",
        "borderRadius",
        "@mui/system/esm/borders.js",
      ],
      [
        "Box",
        "default",
        "@mui/system/esm/Box/Box.js",
      ],
      [
        "breakpoints",
        "default",
        "@mui/system/esm/breakpoints.js",
      ],
      [
        "handleBreakpoints",
        "handleBreakpoints",
        "@mui/system/esm/breakpoints.js",
      ],
      [
        "mergeBreakpointsInOrder",
        "mergeBreakpointsInOrder",
        "@mui/system/esm/breakpoints.js",
      ],
      [
        "unstable_resolveBreakpointValues",
        "resolveBreakpointValues",
        "@mui/system/esm/breakpoints.js",
      ],
      [
        "hexToRgb",
        "hexToRgb",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "decomposeColor",
        "decomposeColor",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "colorChannel",
        "colorChannel",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "private_safeColorChannel",
        "private_safeColorChannel",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "recomposeColor",
        "recomposeColor",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "rgbToHex",
        "rgbToHex",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "hslToRgb",
        "hslToRgb",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "getLuminance",
        "getLuminance",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "getContrastRatio",
        "getContrastRatio",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "alpha",
        "alpha",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "private_safeAlpha",
        "private_safeAlpha",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "darken",
        "darken",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "private_safeDarken",
        "private_safeDarken",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "lighten",
        "lighten",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "private_safeLighten",
        "private_safeLighten",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "emphasize",
        "emphasize",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "private_safeEmphasize",
        "private_safeEmphasize",
        "@mui/system/esm/colorManipulator.js",
      ],
      [
        "compose",
        "default",
        "@mui/system/esm/compose.js",
      ],
      [
        "Container",
        "default",
        "@mui/system/esm/Container/Container.js",
      ],
      [
        "containerClasses",
        "default",
        "@mui/system/esm/Container/containerClasses.js",
      ],
      [
        "getContainerUtilityClass",
        "getContainerUtilityClass",
        "@mui/system/esm/Container/containerClasses.js",
      ],
      [
        "createContainer",
        "default",
        "@mui/system/esm/Container/createContainer.js",
      ],
      [
        "createBox",
        "default",
        "@mui/system/esm/createBox.js",
      ],
      [
        "createStyled",
        "default",
        "@mui/system/esm/createStyled.js",
      ],
      [
        "shouldForwardProp",
        "shouldForwardProp",
        "@mui/system/esm/createStyled.js",
      ],
      [
        "systemDefaultTheme",
        "systemDefaultTheme",
        "@mui/system/esm/createStyled.js",
      ],
      [
        "createBreakpoints",
        "default",
        "@mui/system/esm/createTheme/createBreakpoints.js",
      ],
      [
        "createSpacing",
        "default",
        "@mui/system/esm/createTheme/createSpacing.js",
      ],
      [
        "createTheme",
        "default",
        "@mui/system/esm/createTheme/createTheme.js",
      ],
      [
        "shape",
        "default",
        "@mui/system/esm/createTheme/shape.js",
      ],
      [
        "grid",
        "default",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gap",
        "gap",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "columnGap",
        "columnGap",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "rowGap",
        "rowGap",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridColumn",
        "gridColumn",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridRow",
        "gridRow",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridAutoFlow",
        "gridAutoFlow",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridAutoColumns",
        "gridAutoColumns",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridAutoRows",
        "gridAutoRows",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridTemplateColumns",
        "gridTemplateColumns",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridTemplateRows",
        "gridTemplateRows",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridTemplateAreas",
        "gridTemplateAreas",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "gridArea",
        "gridArea",
        "@mui/system/esm/cssGrid.js",
      ],
      [
        "unstable_createCssVarsProvider",
        "default",
        "@mui/system/esm/cssVars/createCssVarsProvider.js",
      ],
      [
        "unstable_createGetCssVar",
        "default",
        "@mui/system/esm/cssVars/createGetCssVar.js",
      ],
      [
        "display",
        "default",
        "@mui/system/esm/display.js",
      ],
      [
        "flexbox",
        "default",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "flexBasis",
        "flexBasis",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "flexDirection",
        "flexDirection",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "flexWrap",
        "flexWrap",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "justifyContent",
        "justifyContent",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "alignItems",
        "alignItems",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "alignContent",
        "alignContent",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "order",
        "order",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "flex",
        "flex",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "flexGrow",
        "flexGrow",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "flexShrink",
        "flexShrink",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "alignSelf",
        "alignSelf",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "justifyItems",
        "justifyItems",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "justifySelf",
        "justifySelf",
        "@mui/system/esm/flexbox.js",
      ],
      [
        "unstable_getThemeValue",
        "default",
        "@mui/system/esm/getThemeValue.js",
      ],
      [
        "experimental_sx",
        "experimental_sx",
        "@mui/system/esm/index.js",
      ],
      [
        "palette",
        "default",
        "@mui/system/esm/palette.js",
      ],
      [
        "paletteTransform",
        "paletteTransform",
        "@mui/system/esm/palette.js",
      ],
      [
        "color",
        "color",
        "@mui/system/esm/palette.js",
      ],
      [
        "bgcolor",
        "bgcolor",
        "@mui/system/esm/palette.js",
      ],
      [
        "backgroundColor",
        "backgroundColor",
        "@mui/system/esm/palette.js",
      ],
      [
        "positions",
        "default",
        "@mui/system/esm/positions.js",
      ],
      [
        "position",
        "position",
        "@mui/system/esm/positions.js",
      ],
      [
        "zIndex",
        "zIndex",
        "@mui/system/esm/positions.js",
      ],
      [
        "top",
        "top",
        "@mui/system/esm/positions.js",
      ],
      [
        "right",
        "right",
        "@mui/system/esm/positions.js",
      ],
      [
        "bottom",
        "bottom",
        "@mui/system/esm/positions.js",
      ],
      [
        "left",
        "left",
        "@mui/system/esm/positions.js",
      ],
      [
        "responsivePropType",
        "default",
        "@mui/system/esm/responsivePropType.js",
      ],
      [
        "shadows",
        "default",
        "@mui/system/esm/shadows.js",
      ],
      [
        "sizing",
        "default",
        "@mui/system/esm/sizing.js",
      ],
      [
        "sizingTransform",
        "sizingTransform",
        "@mui/system/esm/sizing.js",
      ],
      [
        "width",
        "width",
        "@mui/system/esm/sizing.js",
      ],
      [
        "maxWidth",
        "maxWidth",
        "@mui/system/esm/sizing.js",
      ],
      [
        "minWidth",
        "minWidth",
        "@mui/system/esm/sizing.js",
      ],
      [
        "height",
        "height",
        "@mui/system/esm/sizing.js",
      ],
      [
        "maxHeight",
        "maxHeight",
        "@mui/system/esm/sizing.js",
      ],
      [
        "minHeight",
        "minHeight",
        "@mui/system/esm/sizing.js",
      ],
      [
        "sizeWidth",
        "sizeWidth",
        "@mui/system/esm/sizing.js",
      ],
      [
        "sizeHeight",
        "sizeHeight",
        "@mui/system/esm/sizing.js",
      ],
      [
        "boxSizing",
        "boxSizing",
        "@mui/system/esm/sizing.js",
      ],
      [
        "spacing",
        "default",
        "@mui/system/esm/spacing.js",
      ],
      [
        "marginKeys",
        "marginKeys",
        "@mui/system/esm/spacing.js",
      ],
      [
        "paddingKeys",
        "paddingKeys",
        "@mui/system/esm/spacing.js",
      ],
      [
        "createUnaryUnit",
        "createUnaryUnit",
        "@mui/system/esm/spacing.js",
      ],
      [
        "createUnarySpacing",
        "createUnarySpacing",
        "@mui/system/esm/spacing.js",
      ],
      [
        "getValue",
        "getValue",
        "@mui/system/esm/spacing.js",
      ],
      [
        "getStyleFromPropValue",
        "getStyleFromPropValue",
        "@mui/system/esm/spacing.js",
      ],
      [
        "margin",
        "margin",
        "@mui/system/esm/spacing.js",
      ],
      [
        "padding",
        "padding",
        "@mui/system/esm/spacing.js",
      ],
      [
        "createStack",
        "default",
        "@mui/system/esm/Stack/createStack.js",
      ],
      [
        "Stack",
        "default",
        "@mui/system/esm/Stack/Stack.js",
      ],
      [
        "stackClasses",
        "default",
        "@mui/system/esm/Stack/stackClasses.js",
      ],
      [
        "getStackUtilityClass",
        "getStackUtilityClass",
        "@mui/system/esm/Stack/stackClasses.js",
      ],
      [
        "getPath",
        "getPath",
        "@mui/system/esm/style.js",
      ],
      [
        "getStyleValue",
        "getStyleValue",
        "@mui/system/esm/style.js",
      ],
      [
        "style",
        "default",
        "@mui/system/esm/style.js",
      ],
      [
        "styled",
        "default",
        "@mui/system/esm/styled.js",
      ],
      [
        "unstable_defaultSxConfig",
        "default",
        "@mui/system/esm/styleFunctionSx/defaultSxConfig.js",
      ],
      [
        "unstable_extendSxProp",
        "default",
        "@mui/system/esm/styleFunctionSx/extendSxProp.js",
      ],
      [
        "unstable_styleFunctionSx",
        "default",
        "@mui/system/esm/styleFunctionSx/styleFunctionSx.js",
      ],
      [
        "unstable_createStyleFunctionSx",
        "unstable_createStyleFunctionSx",
        "@mui/system/esm/styleFunctionSx/styleFunctionSx.js",
      ],
      [
        "ThemeProvider",
        "default",
        "@mui/system/esm/ThemeProvider/ThemeProvider.js",
      ],
      [
        "typography",
        "default",
        "@mui/system/esm/typography.js",
      ],
      [
        "fontFamily",
        "fontFamily",
        "@mui/system/esm/typography.js",
      ],
      [
        "fontSize",
        "fontSize",
        "@mui/system/esm/typography.js",
      ],
      [
        "fontStyle",
        "fontStyle",
        "@mui/system/esm/typography.js",
      ],
      [
        "fontWeight",
        "fontWeight",
        "@mui/system/esm/typography.js",
      ],
      [
        "letterSpacing",
        "letterSpacing",
        "@mui/system/esm/typography.js",
      ],
      [
        "textTransform",
        "textTransform",
        "@mui/system/esm/typography.js",
      ],
      [
        "lineHeight",
        "lineHeight",
        "@mui/system/esm/typography.js",
      ],
      [
        "textAlign",
        "textAlign",
        "@mui/system/esm/typography.js",
      ],
      [
        "typographyVariant",
        "typographyVariant",
        "@mui/system/esm/typography.js",
      ],
      [
        "createGrid",
        "default",
        "@mui/system/esm/Unstable_Grid/createGrid.js",
      ],
      [
        "Unstable_Grid",
        "default",
        "@mui/system/esm/Unstable_Grid/Grid.js",
      ],
      [
        "gridClasses",
        "default",
        "@mui/system/esm/Unstable_Grid/gridClasses.js",
      ],
      [
        "getGridUtilityClass",
        "getGridUtilityClass",
        "@mui/system/esm/Unstable_Grid/gridClasses.js",
      ],
      [
        "useTheme",
        "default",
        "@mui/system/esm/useTheme.js",
      ],
      [
        "getThemeProps",
        "default",
        "@mui/system/esm/useThemeProps/getThemeProps.js",
      ],
      [
        "useThemeProps",
        "default",
        "@mui/system/esm/useThemeProps/useThemeProps.js",
      ],
      [
        "useThemeWithoutDefault",
        "default",
        "@mui/system/esm/useThemeWithoutDefault.js",
      ],
    ]
  `);
});
