"use strict";

const testExports = require("../../testExports");

test("exports", () => {
  expect(testExports("@material-ui/system")).toMatchInlineSnapshot(`
    [
      [
        "borders",
        "default",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "border",
        "border",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "borderTop",
        "borderTop",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "borderRight",
        "borderRight",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "borderBottom",
        "borderBottom",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "borderLeft",
        "borderLeft",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "borderColor",
        "borderColor",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "borderRadius",
        "borderRadius",
        "@material-ui/system/esm/borders.js",
      ],
      [
        "breakpoints",
        "default",
        "@material-ui/system/esm/breakpoints.js",
      ],
      [
        "compose",
        "default",
        "@material-ui/system/esm/compose.js",
      ],
      [
        "display",
        "default",
        "@material-ui/system/esm/display.js",
      ],
      [
        "flexbox",
        "default",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "flexBasis",
        "flexBasis",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "flexDirection",
        "flexDirection",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "flexWrap",
        "flexWrap",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "justifyContent",
        "justifyContent",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "alignItems",
        "alignItems",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "alignContent",
        "alignContent",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "order",
        "order",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "flex",
        "flex",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "flexGrow",
        "flexGrow",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "flexShrink",
        "flexShrink",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "alignSelf",
        "alignSelf",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "justifyItems",
        "justifyItems",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "justifySelf",
        "justifySelf",
        "@material-ui/system/esm/flexbox.js",
      ],
      [
        "grid",
        "default",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridGap",
        "gridGap",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridColumnGap",
        "gridColumnGap",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridRowGap",
        "gridRowGap",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridColumn",
        "gridColumn",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridRow",
        "gridRow",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridAutoFlow",
        "gridAutoFlow",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridAutoColumns",
        "gridAutoColumns",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridAutoRows",
        "gridAutoRows",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridTemplateColumns",
        "gridTemplateColumns",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridTemplateRows",
        "gridTemplateRows",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridTemplateAreas",
        "gridTemplateAreas",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "gridArea",
        "gridArea",
        "@material-ui/system/esm/grid.js",
      ],
      [
        "palette",
        "default",
        "@material-ui/system/esm/palette.js",
      ],
      [
        "color",
        "color",
        "@material-ui/system/esm/palette.js",
      ],
      [
        "bgcolor",
        "bgcolor",
        "@material-ui/system/esm/palette.js",
      ],
      [
        "positions",
        "default",
        "@material-ui/system/esm/positions.js",
      ],
      [
        "position",
        "position",
        "@material-ui/system/esm/positions.js",
      ],
      [
        "zIndex",
        "zIndex",
        "@material-ui/system/esm/positions.js",
      ],
      [
        "top",
        "top",
        "@material-ui/system/esm/positions.js",
      ],
      [
        "right",
        "right",
        "@material-ui/system/esm/positions.js",
      ],
      [
        "bottom",
        "bottom",
        "@material-ui/system/esm/positions.js",
      ],
      [
        "left",
        "left",
        "@material-ui/system/esm/positions.js",
      ],
      [
        "shadows",
        "default",
        "@material-ui/system/esm/shadows.js",
      ],
      [
        "sizing",
        "default",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "width",
        "width",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "maxWidth",
        "maxWidth",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "minWidth",
        "minWidth",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "height",
        "height",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "maxHeight",
        "maxHeight",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "minHeight",
        "minHeight",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "sizeWidth",
        "sizeWidth",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "sizeHeight",
        "sizeHeight",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "boxSizing",
        "boxSizing",
        "@material-ui/system/esm/sizing.js",
      ],
      [
        "spacing",
        "default",
        "@material-ui/system/esm/spacing.js",
      ],
      [
        "createUnarySpacing",
        "createUnarySpacing",
        "@material-ui/system/esm/spacing.js",
      ],
      [
        "style",
        "default",
        "@material-ui/system/esm/style.js",
      ],
      [
        "styleFunctionSx",
        "default",
        "@material-ui/system/esm/styleFunctionSx.js",
      ],
      [
        "css",
        "css",
        "@material-ui/system/esm/styleFunctionSx.js",
      ],
      [
        "typography",
        "default",
        "@material-ui/system/esm/typography.js",
      ],
      [
        "fontFamily",
        "fontFamily",
        "@material-ui/system/esm/typography.js",
      ],
      [
        "fontSize",
        "fontSize",
        "@material-ui/system/esm/typography.js",
      ],
      [
        "fontStyle",
        "fontStyle",
        "@material-ui/system/esm/typography.js",
      ],
      [
        "fontWeight",
        "fontWeight",
        "@material-ui/system/esm/typography.js",
      ],
      [
        "letterSpacing",
        "letterSpacing",
        "@material-ui/system/esm/typography.js",
      ],
      [
        "lineHeight",
        "lineHeight",
        "@material-ui/system/esm/typography.js",
      ],
      [
        "textAlign",
        "textAlign",
        "@material-ui/system/esm/typography.js",
      ],
    ]
  `);
});
