import { expect, test } from "vitest";
import { testExports } from "../../utils.js";

test("exports", () => {
  expect(testExports("@material-ui/lab")).toMatchInlineSnapshot(`
    [
      [
        "Alert",
        "default",
        "@material-ui/lab/esm/Alert/Alert.js",
      ],
      [
        "AlertTitle",
        "default",
        "@material-ui/lab/esm/AlertTitle/AlertTitle.js",
      ],
      [
        "Autocomplete",
        "default",
        "@material-ui/lab/esm/Autocomplete/Autocomplete.js",
      ],
      [
        "AvatarGroup",
        "default",
        "@material-ui/lab/esm/AvatarGroup/AvatarGroup.js",
      ],
      [
        "Pagination",
        "default",
        "@material-ui/lab/esm/Pagination/Pagination.js",
      ],
      [
        "usePagination",
        "default",
        "@material-ui/lab/esm/Pagination/usePagination.js",
      ],
      [
        "PaginationItem",
        "default",
        "@material-ui/lab/esm/PaginationItem/PaginationItem.js",
      ],
      [
        "Rating",
        "default",
        "@material-ui/lab/esm/Rating/Rating.js",
      ],
      [
        "Skeleton",
        "default",
        "@material-ui/lab/esm/Skeleton/Skeleton.js",
      ],
      [
        "SpeedDial",
        "default",
        "@material-ui/lab/esm/SpeedDial/SpeedDial.js",
      ],
      [
        "SpeedDialAction",
        "default",
        "@material-ui/lab/esm/SpeedDialAction/SpeedDialAction.js",
      ],
      [
        "SpeedDialIcon",
        "default",
        "@material-ui/lab/esm/SpeedDialIcon/SpeedDialIcon.js",
      ],
      [
        "TabContext",
        "default",
        "@material-ui/lab/esm/TabContext/TabContext.js",
      ],
      [
        "useTabContext",
        "useTabContext",
        "@material-ui/lab/esm/TabContext/TabContext.js",
      ],
      [
        "getPanelId",
        "getPanelId",
        "@material-ui/lab/esm/TabContext/TabContext.js",
      ],
      [
        "getTabId",
        "getTabId",
        "@material-ui/lab/esm/TabContext/TabContext.js",
      ],
      [
        "TabList",
        "default",
        "@material-ui/lab/esm/TabList/TabList.js",
      ],
      [
        "TabPanel",
        "default",
        "@material-ui/lab/esm/TabPanel/TabPanel.js",
      ],
      [
        "Timeline",
        "default",
        "@material-ui/lab/esm/Timeline/Timeline.js",
      ],
      [
        "TimelineConnector",
        "default",
        "@material-ui/lab/esm/TimelineConnector/TimelineConnector.js",
      ],
      [
        "TimelineContent",
        "default",
        "@material-ui/lab/esm/TimelineContent/TimelineContent.js",
      ],
      [
        "TimelineDot",
        "default",
        "@material-ui/lab/esm/TimelineDot/TimelineDot.js",
      ],
      [
        "TimelineItem",
        "default",
        "@material-ui/lab/esm/TimelineItem/TimelineItem.js",
      ],
      [
        "TimelineOppositeContent",
        "default",
        "@material-ui/lab/esm/TimelineOppositeContent/TimelineOppositeContent.js",
      ],
      [
        "TimelineSeparator",
        "default",
        "@material-ui/lab/esm/TimelineSeparator/TimelineSeparator.js",
      ],
      [
        "ToggleButton",
        "default",
        "@material-ui/lab/esm/ToggleButton/ToggleButton.js",
      ],
      [
        "ToggleButtonGroup",
        "default",
        "@material-ui/lab/esm/ToggleButtonGroup/ToggleButtonGroup.js",
      ],
      [
        "TreeItem",
        "default",
        "@material-ui/lab/esm/TreeItem/TreeItem.js",
      ],
      [
        "TreeView",
        "default",
        "@material-ui/lab/esm/TreeView/TreeView.js",
      ],
      [
        "createFilterOptions",
        "createFilterOptions",
        "@material-ui/lab/esm/useAutocomplete/index.js",
      ],
      [
        "useAutocomplete",
        "default",
        "@material-ui/lab/esm/useAutocomplete/useAutocomplete.js",
      ],
    ]
  `);
});
