"use strict";

const testExports = require("../../testExports");

test("exports", () => {
  expect(testExports("@material-ui/core")).toMatchInlineSnapshot(`
[
  [
    "Accordion",
    "default",
    "@material-ui/core/esm/Accordion/Accordion.js",
  ],
  [
    "AccordionActions",
    "default",
    "@material-ui/core/esm/AccordionActions/AccordionActions.js",
  ],
  [
    "AccordionDetails",
    "default",
    "@material-ui/core/esm/AccordionDetails/AccordionDetails.js",
  ],
  [
    "AccordionSummary",
    "default",
    "@material-ui/core/esm/AccordionSummary/AccordionSummary.js",
  ],
  [
    "AppBar",
    "default",
    "@material-ui/core/esm/AppBar/AppBar.js",
  ],
  [
    "Avatar",
    "default",
    "@material-ui/core/esm/Avatar/Avatar.js",
  ],
  [
    "Backdrop",
    "default",
    "@material-ui/core/esm/Backdrop/Backdrop.js",
  ],
  [
    "Badge",
    "default",
    "@material-ui/core/esm/Badge/Badge.js",
  ],
  [
    "BottomNavigation",
    "default",
    "@material-ui/core/esm/BottomNavigation/BottomNavigation.js",
  ],
  [
    "BottomNavigationAction",
    "default",
    "@material-ui/core/esm/BottomNavigationAction/BottomNavigationAction.js",
  ],
  [
    "Box",
    "default",
    "@material-ui/core/esm/Box/Box.js",
  ],
  [
    "styleFunction",
    "styleFunction",
    "@material-ui/core/esm/Box/Box.js",
  ],
  [
    "Breadcrumbs",
    "default",
    "@material-ui/core/esm/Breadcrumbs/Breadcrumbs.js",
  ],
  [
    "Button",
    "default",
    "@material-ui/core/esm/Button/Button.js",
  ],
  [
    "ButtonBase",
    "default",
    "@material-ui/core/esm/ButtonBase/ButtonBase.js",
  ],
  [
    "ButtonGroup",
    "default",
    "@material-ui/core/esm/ButtonGroup/ButtonGroup.js",
  ],
  [
    "Card",
    "default",
    "@material-ui/core/esm/Card/Card.js",
  ],
  [
    "CardActionArea",
    "default",
    "@material-ui/core/esm/CardActionArea/CardActionArea.js",
  ],
  [
    "CardActions",
    "default",
    "@material-ui/core/esm/CardActions/CardActions.js",
  ],
  [
    "CardContent",
    "default",
    "@material-ui/core/esm/CardContent/CardContent.js",
  ],
  [
    "CardHeader",
    "default",
    "@material-ui/core/esm/CardHeader/CardHeader.js",
  ],
  [
    "CardMedia",
    "default",
    "@material-ui/core/esm/CardMedia/CardMedia.js",
  ],
  [
    "Checkbox",
    "default",
    "@material-ui/core/esm/Checkbox/Checkbox.js",
  ],
  [
    "Chip",
    "default",
    "@material-ui/core/esm/Chip/Chip.js",
  ],
  [
    "CircularProgress",
    "default",
    "@material-ui/core/esm/CircularProgress/CircularProgress.js",
  ],
  [
    "ClickAwayListener",
    "default",
    "@material-ui/core/esm/ClickAwayListener/ClickAwayListener.js",
  ],
  [
    "Collapse",
    "default",
    "@material-ui/core/esm/Collapse/Collapse.js",
  ],
  [
    "colors",
    "*",
    "@material-ui/core/esm/colors/index.js",
  ],
  [
    "Container",
    "default",
    "@material-ui/core/esm/Container/Container.js",
  ],
  [
    "CssBaseline",
    "default",
    "@material-ui/core/esm/CssBaseline/CssBaseline.js",
  ],
  [
    "Dialog",
    "default",
    "@material-ui/core/esm/Dialog/Dialog.js",
  ],
  [
    "DialogActions",
    "default",
    "@material-ui/core/esm/DialogActions/DialogActions.js",
  ],
  [
    "DialogContent",
    "default",
    "@material-ui/core/esm/DialogContent/DialogContent.js",
  ],
  [
    "DialogContentText",
    "default",
    "@material-ui/core/esm/DialogContentText/DialogContentText.js",
  ],
  [
    "DialogTitle",
    "default",
    "@material-ui/core/esm/DialogTitle/DialogTitle.js",
  ],
  [
    "Divider",
    "default",
    "@material-ui/core/esm/Divider/Divider.js",
  ],
  [
    "Drawer",
    "default",
    "@material-ui/core/esm/Drawer/Drawer.js",
  ],
  [
    "ExpansionPanel",
    "default",
    "@material-ui/core/esm/ExpansionPanel/ExpansionPanel.js",
  ],
  [
    "ExpansionPanelActions",
    "default",
    "@material-ui/core/esm/ExpansionPanelActions/ExpansionPanelActions.js",
  ],
  [
    "ExpansionPanelDetails",
    "default",
    "@material-ui/core/esm/ExpansionPanelDetails/ExpansionPanelDetails.js",
  ],
  [
    "ExpansionPanelSummary",
    "default",
    "@material-ui/core/esm/ExpansionPanelSummary/ExpansionPanelSummary.js",
  ],
  [
    "Fab",
    "default",
    "@material-ui/core/esm/Fab/Fab.js",
  ],
  [
    "Fade",
    "default",
    "@material-ui/core/esm/Fade/Fade.js",
  ],
  [
    "FilledInput",
    "default",
    "@material-ui/core/esm/FilledInput/FilledInput.js",
  ],
  [
    "FormControl",
    "default",
    "@material-ui/core/esm/FormControl/FormControl.js",
  ],
  [
    "useFormControl",
    "default",
    "@material-ui/core/esm/FormControl/useFormControl.js",
  ],
  [
    "FormControlLabel",
    "default",
    "@material-ui/core/esm/FormControlLabel/FormControlLabel.js",
  ],
  [
    "FormGroup",
    "default",
    "@material-ui/core/esm/FormGroup/FormGroup.js",
  ],
  [
    "FormHelperText",
    "default",
    "@material-ui/core/esm/FormHelperText/FormHelperText.js",
  ],
  [
    "FormLabel",
    "default",
    "@material-ui/core/esm/FormLabel/FormLabel.js",
  ],
  [
    "Grid",
    "default",
    "@material-ui/core/esm/Grid/Grid.js",
  ],
  [
    "GridList",
    "default",
    "@material-ui/core/esm/GridList/GridList.js",
  ],
  [
    "GridListTile",
    "default",
    "@material-ui/core/esm/GridListTile/GridListTile.js",
  ],
  [
    "GridListTileBar",
    "default",
    "@material-ui/core/esm/GridListTileBar/GridListTileBar.js",
  ],
  [
    "Grow",
    "default",
    "@material-ui/core/esm/Grow/Grow.js",
  ],
  [
    "Hidden",
    "default",
    "@material-ui/core/esm/Hidden/Hidden.js",
  ],
  [
    "Icon",
    "default",
    "@material-ui/core/esm/Icon/Icon.js",
  ],
  [
    "IconButton",
    "default",
    "@material-ui/core/esm/IconButton/IconButton.js",
  ],
  [
    "ImageList",
    "default",
    "@material-ui/core/esm/ImageList/ImageList.js",
  ],
  [
    "ImageListItem",
    "default",
    "@material-ui/core/esm/ImageListItem/ImageListItem.js",
  ],
  [
    "ImageListItemBar",
    "default",
    "@material-ui/core/esm/ImageListItemBar/ImageListItemBar.js",
  ],
  [
    "Input",
    "default",
    "@material-ui/core/esm/Input/Input.js",
  ],
  [
    "InputAdornment",
    "default",
    "@material-ui/core/esm/InputAdornment/InputAdornment.js",
  ],
  [
    "InputBase",
    "default",
    "@material-ui/core/esm/InputBase/InputBase.js",
  ],
  [
    "InputLabel",
    "default",
    "@material-ui/core/esm/InputLabel/InputLabel.js",
  ],
  [
    "LinearProgress",
    "default",
    "@material-ui/core/esm/LinearProgress/LinearProgress.js",
  ],
  [
    "Link",
    "default",
    "@material-ui/core/esm/Link/Link.js",
  ],
  [
    "List",
    "default",
    "@material-ui/core/esm/List/List.js",
  ],
  [
    "ListItem",
    "default",
    "@material-ui/core/esm/ListItem/ListItem.js",
  ],
  [
    "ListItemAvatar",
    "default",
    "@material-ui/core/esm/ListItemAvatar/ListItemAvatar.js",
  ],
  [
    "ListItemIcon",
    "default",
    "@material-ui/core/esm/ListItemIcon/ListItemIcon.js",
  ],
  [
    "ListItemSecondaryAction",
    "default",
    "@material-ui/core/esm/ListItemSecondaryAction/ListItemSecondaryAction.js",
  ],
  [
    "ListItemText",
    "default",
    "@material-ui/core/esm/ListItemText/ListItemText.js",
  ],
  [
    "ListSubheader",
    "default",
    "@material-ui/core/esm/ListSubheader/ListSubheader.js",
  ],
  [
    "Menu",
    "default",
    "@material-ui/core/esm/Menu/Menu.js",
  ],
  [
    "MenuItem",
    "default",
    "@material-ui/core/esm/MenuItem/MenuItem.js",
  ],
  [
    "MenuList",
    "default",
    "@material-ui/core/esm/MenuList/MenuList.js",
  ],
  [
    "MobileStepper",
    "default",
    "@material-ui/core/esm/MobileStepper/MobileStepper.js",
  ],
  [
    "Modal",
    "default",
    "@material-ui/core/esm/Modal/Modal.js",
  ],
  [
    "ModalManager",
    "ModalManager",
    "@material-ui/core/esm/Modal/ModalManager.js",
  ],
  [
    "NativeSelect",
    "default",
    "@material-ui/core/esm/NativeSelect/NativeSelect.js",
  ],
  [
    "NoSsr",
    "default",
    "@material-ui/core/esm/NoSsr/NoSsr.js",
  ],
  [
    "OutlinedInput",
    "default",
    "@material-ui/core/esm/OutlinedInput/OutlinedInput.js",
  ],
  [
    "Paper",
    "default",
    "@material-ui/core/esm/Paper/Paper.js",
  ],
  [
    "Popover",
    "default",
    "@material-ui/core/esm/Popover/Popover.js",
  ],
  [
    "Popper",
    "default",
    "@material-ui/core/esm/Popper/Popper.js",
  ],
  [
    "Portal",
    "default",
    "@material-ui/core/esm/Portal/Portal.js",
  ],
  [
    "Radio",
    "default",
    "@material-ui/core/esm/Radio/Radio.js",
  ],
  [
    "RadioGroup",
    "default",
    "@material-ui/core/esm/RadioGroup/RadioGroup.js",
  ],
  [
    "useRadioGroup",
    "default",
    "@material-ui/core/esm/RadioGroup/useRadioGroup.js",
  ],
  [
    "RootRef",
    "default",
    "@material-ui/core/esm/RootRef/RootRef.js",
  ],
  [
    "Select",
    "default",
    "@material-ui/core/esm/Select/Select.js",
  ],
  [
    "Slide",
    "default",
    "@material-ui/core/esm/Slide/Slide.js",
  ],
  [
    "Slider",
    "default",
    "@material-ui/core/esm/Slider/Slider.js",
  ],
  [
    "Snackbar",
    "default",
    "@material-ui/core/esm/Snackbar/Snackbar.js",
  ],
  [
    "SnackbarContent",
    "default",
    "@material-ui/core/esm/SnackbarContent/SnackbarContent.js",
  ],
  [
    "Step",
    "default",
    "@material-ui/core/esm/Step/Step.js",
  ],
  [
    "StepButton",
    "default",
    "@material-ui/core/esm/StepButton/StepButton.js",
  ],
  [
    "StepConnector",
    "default",
    "@material-ui/core/esm/StepConnector/StepConnector.js",
  ],
  [
    "StepContent",
    "default",
    "@material-ui/core/esm/StepContent/StepContent.js",
  ],
  [
    "StepIcon",
    "default",
    "@material-ui/core/esm/StepIcon/StepIcon.js",
  ],
  [
    "StepLabel",
    "default",
    "@material-ui/core/esm/StepLabel/StepLabel.js",
  ],
  [
    "Stepper",
    "default",
    "@material-ui/core/esm/Stepper/Stepper.js",
  ],
  [
    "hexToRgb",
    "hexToRgb",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "rgbToHex",
    "rgbToHex",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "hslToRgb",
    "hslToRgb",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "decomposeColor",
    "decomposeColor",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "recomposeColor",
    "recomposeColor",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "getContrastRatio",
    "getContrastRatio",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "getLuminance",
    "getLuminance",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "emphasize",
    "emphasize",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "fade",
    "fade",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "alpha",
    "alpha",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "darken",
    "darken",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "lighten",
    "lighten",
    "@material-ui/core/esm/styles/colorManipulator.js",
  ],
  [
    "unstable_createMuiStrictModeTheme",
    "default",
    "@material-ui/core/esm/styles/createMuiStrictModeTheme.js",
  ],
  [
    "createStyles",
    "default",
    "@material-ui/core/esm/styles/createStyles.js",
  ],
  [
    "createMuiTheme",
    "createMuiTheme",
    "@material-ui/core/esm/styles/createTheme.js",
  ],
  [
    "createTheme",
    "default",
    "@material-ui/core/esm/styles/createTheme.js",
  ],
  [
    "makeStyles",
    "default",
    "@material-ui/core/esm/styles/makeStyles.js",
  ],
  [
    "responsiveFontSizes",
    "default",
    "@material-ui/core/esm/styles/responsiveFontSizes.js",
  ],
  [
    "styled",
    "default",
    "@material-ui/core/esm/styles/styled.js",
  ],
  [
    "easing",
    "easing",
    "@material-ui/core/esm/styles/transitions.js",
  ],
  [
    "duration",
    "duration",
    "@material-ui/core/esm/styles/transitions.js",
  ],
  [
    "useTheme",
    "default",
    "@material-ui/core/esm/styles/useTheme.js",
  ],
  [
    "withStyles",
    "default",
    "@material-ui/core/esm/styles/withStyles.js",
  ],
  [
    "withTheme",
    "default",
    "@material-ui/core/esm/styles/withTheme.js",
  ],
  [
    "SvgIcon",
    "default",
    "@material-ui/core/esm/SvgIcon/SvgIcon.js",
  ],
  [
    "SwipeableDrawer",
    "default",
    "@material-ui/core/esm/SwipeableDrawer/SwipeableDrawer.js",
  ],
  [
    "Switch",
    "default",
    "@material-ui/core/esm/Switch/Switch.js",
  ],
  [
    "Tab",
    "default",
    "@material-ui/core/esm/Tab/Tab.js",
  ],
  [
    "Table",
    "default",
    "@material-ui/core/esm/Table/Table.js",
  ],
  [
    "TableBody",
    "default",
    "@material-ui/core/esm/TableBody/TableBody.js",
  ],
  [
    "TableCell",
    "default",
    "@material-ui/core/esm/TableCell/TableCell.js",
  ],
  [
    "TableContainer",
    "default",
    "@material-ui/core/esm/TableContainer/TableContainer.js",
  ],
  [
    "TableFooter",
    "default",
    "@material-ui/core/esm/TableFooter/TableFooter.js",
  ],
  [
    "TableHead",
    "default",
    "@material-ui/core/esm/TableHead/TableHead.js",
  ],
  [
    "TablePagination",
    "default",
    "@material-ui/core/esm/TablePagination/TablePagination.js",
  ],
  [
    "TableRow",
    "default",
    "@material-ui/core/esm/TableRow/TableRow.js",
  ],
  [
    "TableSortLabel",
    "default",
    "@material-ui/core/esm/TableSortLabel/TableSortLabel.js",
  ],
  [
    "Tabs",
    "default",
    "@material-ui/core/esm/Tabs/Tabs.js",
  ],
  [
    "TabScrollButton",
    "default",
    "@material-ui/core/esm/TabScrollButton/TabScrollButton.js",
  ],
  [
    "TextareaAutosize",
    "default",
    "@material-ui/core/esm/TextareaAutosize/TextareaAutosize.js",
  ],
  [
    "TextField",
    "default",
    "@material-ui/core/esm/TextField/TextField.js",
  ],
  [
    "Toolbar",
    "default",
    "@material-ui/core/esm/Toolbar/Toolbar.js",
  ],
  [
    "Tooltip",
    "default",
    "@material-ui/core/esm/Tooltip/Tooltip.js",
  ],
  [
    "Typography",
    "default",
    "@material-ui/core/esm/Typography/Typography.js",
  ],
  [
    "Unstable_TrapFocus",
    "default",
    "@material-ui/core/esm/Unstable_TrapFocus/Unstable_TrapFocus.js",
  ],
  [
    "useMediaQuery",
    "default",
    "@material-ui/core/esm/useMediaQuery/useMediaQuery.js",
  ],
  [
    "useScrollTrigger",
    "default",
    "@material-ui/core/esm/useScrollTrigger/useScrollTrigger.js",
  ],
  [
    "capitalize",
    "default",
    "@material-ui/core/esm/utils/capitalize.js",
  ],
  [
    "createChainedFunction",
    "default",
    "@material-ui/core/esm/utils/createChainedFunction.js",
  ],
  [
    "createSvgIcon",
    "default",
    "@material-ui/core/esm/utils/createSvgIcon.js",
  ],
  [
    "debounce",
    "default",
    "@material-ui/core/esm/utils/debounce.js",
  ],
  [
    "deprecatedPropType",
    "default",
    "@material-ui/core/esm/utils/deprecatedPropType.js",
  ],
  [
    "isMuiElement",
    "default",
    "@material-ui/core/esm/utils/isMuiElement.js",
  ],
  [
    "ownerDocument",
    "default",
    "@material-ui/core/esm/utils/ownerDocument.js",
  ],
  [
    "ownerWindow",
    "default",
    "@material-ui/core/esm/utils/ownerWindow.js",
  ],
  [
    "requirePropFactory",
    "default",
    "@material-ui/core/esm/utils/requirePropFactory.js",
  ],
  [
    "setRef",
    "default",
    "@material-ui/core/esm/utils/setRef.js",
  ],
  [
    "unstable_useId",
    "default",
    "@material-ui/core/esm/utils/unstable_useId.js",
  ],
  [
    "unsupportedProp",
    "default",
    "@material-ui/core/esm/utils/unsupportedProp.js",
  ],
  [
    "useControlled",
    "default",
    "@material-ui/core/esm/utils/useControlled.js",
  ],
  [
    "useEventCallback",
    "default",
    "@material-ui/core/esm/utils/useEventCallback.js",
  ],
  [
    "useForkRef",
    "default",
    "@material-ui/core/esm/utils/useForkRef.js",
  ],
  [
    "useIsFocusVisible",
    "default",
    "@material-ui/core/esm/utils/useIsFocusVisible.js",
  ],
  [
    "withMobileDialog",
    "default",
    "@material-ui/core/esm/withMobileDialog/withMobileDialog.js",
  ],
  [
    "withWidth",
    "default",
    "@material-ui/core/esm/withWidth/withWidth.js",
  ],
  [
    "isWidthUp",
    "isWidthUp",
    "@material-ui/core/esm/withWidth/withWidth.js",
  ],
  [
    "isWidthDown",
    "isWidthDown",
    "@material-ui/core/esm/withWidth/withWidth.js",
  ],
  [
    "Zoom",
    "default",
    "@material-ui/core/esm/Zoom/Zoom.js",
  ],
  [
    "createGenerateClassName",
    "createGenerateClassName",
    "@material-ui/styles",
  ],
  [
    "jssPreset",
    "jssPreset",
    "@material-ui/styles",
  ],
  [
    "ServerStyleSheets",
    "ServerStyleSheets",
    "@material-ui/styles",
  ],
  [
    "StylesProvider",
    "StylesProvider",
    "@material-ui/styles",
  ],
  [
    "MuiThemeProvider",
    "ThemeProvider",
    "@material-ui/styles",
  ],
  [
    "ThemeProvider",
    "ThemeProvider",
    "@material-ui/styles",
  ],
]
`);
});
