"use strict";

const testExports = require("../../testExports");

test("exports", () => {
  expect(testExports("@mui/core")).toMatchInlineSnapshot(`
    [
      [
        "createFilterOptions",
        "createFilterOptions",
        "@mui/core/AutocompleteUnstyled/useAutocomplete.js",
      ],
      [
        "useAutocomplete",
        "default",
        "@mui/core/AutocompleteUnstyled/useAutocomplete.js",
      ],
      [
        "BackdropUnstyled",
        "default",
        "@mui/core/BackdropUnstyled/BackdropUnstyled.js",
      ],
      [
        "getBackdropUtilityClass",
        "getBackdropUtilityClass",
        "@mui/core/BackdropUnstyled/backdropUnstyledClasses.js",
      ],
      [
        "backdropUnstyledClasses",
        "default",
        "@mui/core/BackdropUnstyled/backdropUnstyledClasses.js",
      ],
      [
        "BadgeUnstyled",
        "default",
        "@mui/core/BadgeUnstyled/BadgeUnstyled.js",
      ],
      [
        "getBadgeUtilityClass",
        "getBadgeUtilityClass",
        "@mui/core/BadgeUnstyled/badgeUnstyledClasses.js",
      ],
      [
        "badgeUnstyledClasses",
        "default",
        "@mui/core/BadgeUnstyled/badgeUnstyledClasses.js",
      ],
      [
        "ButtonUnstyled",
        "default",
        "@mui/core/ButtonUnstyled/ButtonUnstyled.js",
      ],
      [
        "getButtonUnstyledUtilityClass",
        "getButtonUnstyledUtilityClass",
        "@mui/core/ButtonUnstyled/buttonUnstyledClasses.js",
      ],
      [
        "buttonUnstyledClasses",
        "default",
        "@mui/core/ButtonUnstyled/buttonUnstyledClasses.js",
      ],
      [
        "useButton",
        "default",
        "@mui/core/ButtonUnstyled/useButton.js",
      ],
      [
        "unstable_composeClasses",
        "default",
        "@mui/core/composeClasses/composeClasses.js",
      ],
      [
        "FormControlUnstyledContext",
        "default",
        "@mui/core/FormControlUnstyled/FormControlContext.js",
      ],
      [
        "FormControlUnstyled",
        "default",
        "@mui/core/FormControlUnstyled/FormControlUnstyled.js",
      ],
      [
        "formControlUnstyledClasses",
        "default",
        "@mui/core/FormControlUnstyled/formControlUnstyledClasses.js",
      ],
      [
        "getFormControlUnstyledUtilityClasses",
        "getFormControlUnstyledUtilityClasses",
        "@mui/core/FormControlUnstyled/formControlUnstyledClasses.js",
      ],
      [
        "useFormControlUnstyled",
        "default",
        "@mui/core/FormControlUnstyled/useFormControl.js",
      ],
      [
        "unstable_ClassNameGenerator",
        "default",
        "@mui/core/generateUtilityClass/ClassNameGenerator.js",
      ],
      [
        "generateUtilityClass",
        "default",
        "@mui/core/generateUtilityClass/generateUtilityClass.js",
      ],
      [
        "generateUtilityClasses",
        "default",
        "@mui/core/generateUtilityClasses/generateUtilityClasses.js",
      ],
      [
        "InputUnstyled",
        "default",
        "@mui/core/InputUnstyled/InputUnstyled.js",
      ],
      [
        "inputUnstyledClasses",
        "default",
        "@mui/core/InputUnstyled/inputUnstyledClasses.js",
      ],
      [
        "getInputUnstyledUtilityClass",
        "getInputUnstyledUtilityClass",
        "@mui/core/InputUnstyled/inputUnstyledClasses.js",
      ],
      [
        "useInput",
        "default",
        "@mui/core/InputUnstyled/useInput.js",
      ],
      [
        "ModalManager",
        "default",
        "@mui/core/ModalUnstyled/ModalManager.js",
      ],
      [
        "ModalUnstyled",
        "default",
        "@mui/core/ModalUnstyled/ModalUnstyled.js",
      ],
      [
        "getModalUtilityClass",
        "getModalUtilityClass",
        "@mui/core/ModalUnstyled/modalUnstyledClasses.js",
      ],
      [
        "modalUnstyledClasses",
        "default",
        "@mui/core/ModalUnstyled/modalUnstyledClasses.js",
      ],
      [
        "NoSsr",
        "default",
        "@mui/core/NoSsr/NoSsr.js",
      ],
      [
        "Popper",
        "default",
        "@mui/core/Popper/Popper.js",
      ],
      [
        "Portal",
        "default",
        "@mui/core/Portal/Portal.js",
      ],
      [
        "SliderUnstyled",
        "default",
        "@mui/core/SliderUnstyled/SliderUnstyled.js",
      ],
      [
        "sliderUnstyledClasses",
        "default",
        "@mui/core/SliderUnstyled/sliderUnstyledClasses.js",
      ],
      [
        "getSliderUtilityClass",
        "getSliderUtilityClass",
        "@mui/core/SliderUnstyled/sliderUnstyledClasses.js",
      ],
      [
        "SliderValueLabelUnstyled",
        "default",
        "@mui/core/SliderUnstyled/SliderValueLabelUnstyled.js",
      ],
      [
        "SwitchUnstyled",
        "default",
        "@mui/core/SwitchUnstyled/SwitchUnstyled.js",
      ],
      [
        "switchUnstyledClasses",
        "default",
        "@mui/core/SwitchUnstyled/switchUnstyledClasses.js",
      ],
      [
        "getSwitchUnstyledUtilityClass",
        "getSwitchUnstyledUtilityClass",
        "@mui/core/SwitchUnstyled/switchUnstyledClasses.js",
      ],
      [
        "useSwitch",
        "default",
        "@mui/core/SwitchUnstyled/useSwitch.js",
      ],
      [
        "TextareaAutosize",
        "default",
        "@mui/core/TextareaAutosize/TextareaAutosize.js",
      ],
      [
        "Unstable_TrapFocus",
        "default",
        "@mui/core/Unstable_TrapFocus/Unstable_TrapFocus.js",
      ],
      [
        "appendOwnerState",
        "default",
        "@mui/core/utils/appendOwnerState.js",
      ],
      [
        "extractEventHandlers",
        "default",
        "@mui/core/utils/extractEventHandlers.js",
      ],
      [
        "isHostComponent",
        "default",
        "@mui/core/utils/isHostComponent.js",
      ],
    ]
  `);
});
