name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"

      - run: npm ci
      - run: npx tsc
      - run: npm run lint

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npm test

      - uses: codecov/codecov-action@v2.1.0
        if: matrix.os == 'ubuntu-latest' && matrix.node == '14'
