name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: npm test
      - uses: codecov/codecov-action@v2.0.2
